// richOccasionPagesData.js — config for the 7 pages revamped to match
// /cards/leaving-card's rich layout (RichOccasionPage.jsx). Copy below is
// carried over from the existing occasionsData.js / OccasionLandingPage.jsx /
// BabyShowerPage.jsx entries for these occasions, not invented fresh, so the
// SEO copy that was already live keeps working.

const STANDARD_STEPS = [
  { icon: 'Wand', n: '1', title: 'Create the card', desc: 'Choose the occasion, pick a beautiful design, set the delivery time. Done in 90 seconds.' },
  { icon: 'Share2', n: '2', title: 'Share one link', desc: 'Send via WhatsApp, Slack, email or text. Anyone can sign from anywhere — no account needed.' },
  { icon: 'MessageSquare', n: '3', title: 'Everyone signs', desc: 'Contributors add personal messages, photos, GIFs and voice notes at their own pace.' },
  { icon: 'Send', n: '4', title: 'Deliver perfectly', desc: 'Card arrives by email at the exact time you set. With a pooled gift, if you added one.' },
];

const STANDARD_FEATURES = [
  { icon: 'Users', title: 'Unlimited signers', desc: 'No cap on contributors. The whole group signs the same card from one link.' },
  { icon: 'Camera', title: 'Photos, GIFs & voice notes', desc: 'Each signer personalises their message with photos, a GIF, or a voice recording straight from their phone.' },
  { icon: 'Gift', title: 'Pooled gift collection', desc: 'Enable the optional collection pot. Everyone chips in when they sign — no chasing, no awkward transfers.' },
  { icon: 'Clock', title: 'Scheduled delivery', desc: 'Set the exact date and time. You choose the moment it lands.' },
  { icon: 'Globe', title: 'Works for remote groups', desc: 'The link works from any device, anywhere. Nobody gets left out because they\'re remote or abroad.' },
  { icon: 'Film', title: 'Memory Movie™ included', desc: 'Every card auto-generates a 1080p MP4 movie from all the messages, photos and voice notes. Free with every plan.' },
];

export const RICH_OCCASION_PAGES = {

  // ── /cards/sympathy ──────────────────────────────────────────────────────
  sympathy: {
    cardOccasion: 'sympathy', coverOccasion: 'sympathy',
    seoTitle: 'Online Sympathy Card — Group Condolence Cards | Thankeeu',
    seoDescription: 'Send heartfelt condolences from the whole team with an online sympathy card. Everyone signs from one link — kind words, memories and support — delivered privately when needed most.',
    seoKeywords: 'online sympathy card, group sympathy card, condolence card online, sympathy card for colleague, bereavement card group, online condolence card, sympathy card everyone signs',
    canonical: '/cards/sympathy',
    eyebrow: 'Online Sympathy Cards',
    headlineLead: 'Grief shouldn\'t be carried',
    headlineHighlight: 'in a dozen separate messages.',
    subline: 'Give everyone one quiet, private place to share their support, memories and condolences — delivered gently, at a time you choose.',
    ctaLabel: 'Create Sympathy Card — Free',
    trustBadges: ['Free to create', 'No account to sign', 'Private & gentle delivery', 'Works for remote colleagues'],
    howItWorksHeading: 'A quiet way to gather everyone\'s support',
    howItWorksSteps: STANDARD_STEPS,
    featuresHeading: 'Everything a sympathy card needs',
    featuresSub: 'All included in every card. No extras, no tiers, no surprises.',
    features: [
      { icon: 'Users', title: 'Every voice, one card', desc: 'Colleagues, friends and family all add their condolences from one link — no overwhelming flood of separate messages.' },
      { icon: 'Camera', title: 'Share a shared memory', desc: 'Contributors can add a photo alongside their message — often the most meaningful part of a sympathy card.' },
      { icon: 'Gift', title: 'Optional support collection', desc: 'Enable a gift pool for flowers, funeral costs or practical support — contributed quietly, all in one place.' },
      { icon: 'Clock', title: 'Deliver when they\'re ready', desc: 'Set the exact date and time. Deliver a few days later, not in the rawest first moments.' },
      { icon: 'Globe', title: 'Works for remote teams', desc: 'The link works from any device, anywhere — nobody is excluded because they work from another office or country.' },
      { icon: 'Film', title: 'Memory Movie™ included', desc: 'A gentle, cinematic keepsake generated automatically from all the messages and memories shared.' },
    ],
    coverEyebrow: 'Sympathy cover designs',
    coverTitle: 'Choose a cover that offers comfort',
    coverDescription: 'Thoughtful A4 covers for a loss, ready for everyone to add messages, memories, photos and voice notes.',
    faqs: [
      { q: 'How do I send a group sympathy card without making it overwhelming?', a: 'Share the link privately with contributors only, set a close date, and deliver it to the recipient by email. They receive one card they can open when they are ready — not a flood of individual messages.' },
      { q: 'Can contributors add photos to a sympathy card?', a: 'Yes — contributors can add a photo of a shared memory alongside their message, which is often the most meaningful part of a sympathy card.' },
      { q: 'Do contributors need an account?', a: 'No — anyone with the link can sign instantly.' },
      { q: 'Can we include a contribution for the recipient?', a: 'Yes — an optional collection pot lets contributors add a financial gift for flowers, funeral costs, or practical support.' },
    ],
    finalCtaLead: 'Give everyone a place',
    finalCtaHighlight: 'to share their support.',
    finalCtaSub: 'Free to create. Delivered gently, at the moment you choose.',
  },

  // ── /leaving-cards-uk ─────────────────────────────────────────────────────
  'leaving-uk': {
    cardOccasion: 'leaving', coverOccasion: 'leaving',
    seoTitle: 'Online Leaving Cards UK — Group Leaving Cards Everyone Signs | Thankeeu',
    seoDescription: 'Create an online leaving card for a UK colleague in under 2 minutes. The whole team signs from one link — messages, photos, GIFs, voice notes — with a leaving gift collection in GBP. Delivered on their last day.',
    seoKeywords: 'online leaving card UK, leaving card for colleague UK, group leaving card UK, virtual leaving card UK, online farewell card UK, leaving collection UK, farewell card everyone signs UK, leaving card free UK',
    canonical: '/leaving-cards-uk',
    eyebrow: 'Online Leaving Cards — UK',
    headlineLead: 'Their last day deserves',
    headlineHighlight: 'more than a rushed goodbye.',
    subline: 'One link. Everyone signs. The leaving collection sorted at the same time. Delivered on their last day at the exact minute you choose.',
    ctaLabel: 'Create Leaving Card — Free',
    trustBadges: ['Free to create', 'No account to sign', 'GBP gift collection', 'Works for remote teams'],
    howItWorksHeading: 'A proper UK send-off in four steps',
    howItWorksSteps: STANDARD_STEPS,
    featuresHeading: 'Everything a great UK farewell needs',
    featuresSub: 'All included in every card. No extras, no tiers, no surprises.',
    features: STANDARD_FEATURES,
    coverEyebrow: 'Leaving-card covers',
    coverTitle: 'Choose a proper cover for their send-off',
    coverDescription: 'Browse the newest premium A4 designs. Select one to open it in the album studio and add the team\'s messages, photos, GIFs, videos and voice notes.',
    faqs: [
      { q: 'How much does an online leaving card cost in the UK?', a: 'Free to create and collect messages. A small fee, shown upfront in GBP, applies when you send. Significantly less than a decent card from a shop, before delivery is added.' },
      { q: 'Can remote colleagues sign?', a: 'Yes — the link works from any device, anywhere. Your Manchester office, the person on parental leave and the colleague who left last year but wants to sign can all contribute.' },
      { q: 'How does the leaving gift collection work in GBP?', a: 'Enable the optional collection when creating the card. Contributors pay by debit or credit card in GBP — no personal bank accounts involved. The recipient or organiser withdraws the total directly.' },
      { q: 'When should I create the card?', a: 'At least a week before their last day, ideally two — this gives everyone time to sign without rushing. Set delivery for their last morning.' },
    ],
    finalCtaLead: 'Give them the farewell',
    finalCtaHighlight: 'they actually deserve.',
    finalCtaSub: 'Free to create. The whole team signs. Delivered at the exact moment you choose.',
  },

  // ── /birthday-cards-uk ────────────────────────────────────────────────────
  'birthday-uk': {
    cardOccasion: 'birthday', coverOccasion: 'birthday',
    seoTitle: 'Online Birthday Cards UK — Group Birthday Cards for Every Team | Thankeeu',
    seoDescription: 'Create an online birthday group card for a UK colleague in under 2 minutes. Everyone signs from one link — messages, photos, GIFs and voice notes — with a birthday gift collection in GBP. Delivered at midnight.',
    seoKeywords: 'online birthday card UK, group birthday card UK, birthday card for colleague UK, virtual birthday card UK, birthday card everyone signs UK, office birthday card UK, birthday gift collection UK, group ecard UK birthday',
    canonical: '/birthday-cards-uk',
    eyebrow: 'Online Birthday Cards — UK',
    headlineLead: 'Midnight delivery.',
    headlineHighlight: 'Every colleague signs.',
    subline: 'Birthday gift collection in GBP. No carrier bag, no cramped margins — just one card the whole team actually fills with real messages.',
    ctaLabel: 'Create Birthday Card — Free',
    trustBadges: ['Free to create', 'No account to sign', 'GBP gift collection', 'Midnight delivery'],
    howItWorksHeading: 'A birthday card that reaches everyone, in four steps',
    howItWorksSteps: STANDARD_STEPS,
    featuresHeading: 'Everything a great UK birthday card needs',
    featuresSub: 'All included in every card. No extras, no tiers, no surprises.',
    features: STANDARD_FEATURES,
    coverEyebrow: 'Birthday cover designs',
    coverTitle: 'Choose a cover worth celebrating',
    coverDescription: 'Browse the newest premium A4 birthday designs. Select one to open it in the album studio and add the team\'s messages, photos, GIFs, videos and voice notes.',
    faqs: [
      { q: 'How much does an online birthday card cost in the UK?', a: 'Free to create and collect messages. A small sending fee shown upfront in GBP — less than a decent card from a shop, with no delivery charge.' },
      { q: 'Can it be delivered at midnight on their birthday?', a: 'Yes — set any date and time, including midnight, for a surprise the celebrant opens first thing.' },
      { q: 'How does the birthday gift collection work?', a: 'Enable the pool when creating the card. Everyone pays by debit or credit card in GBP when they sign. The recipient withdraws the total directly.' },
      { q: 'Is this better than a paper birthday card?', a: 'For groups: yes. Unlimited messages, remote colleagues included, gift collection built in, delivered on time regardless of day of the week.' },
    ],
    finalCtaLead: 'Give them a birthday',
    finalCtaHighlight: 'the whole team actually shows up for.',
    finalCtaSub: 'Free to create. Everyone signs. Delivered at the exact moment you choose.',
  },

  // ── /cards/baby-shower ────────────────────────────────────────────────────
  'baby-shower': {
    cardOccasion: 'baby_shower', coverOccasion: 'baby_shower',
    seoTitle: 'Online Baby Shower Card — Group Cards & Gift Collections | Thankeeu',
    seoDescription: 'Create an online baby shower card the whole group signs from one link. Warm wishes, photos, GIFs and voice notes — with a pooled baby shower gift. Virtual shower friendly. Free to create.',
    seoKeywords: 'online baby shower card, group baby shower card, baby shower ecard, virtual baby shower card, baby shower gift collection, baby shower card everyone signs, remote baby shower card, baby shower gift fund',
    canonical: '/cards/baby-shower',
    eyebrow: 'Online Baby Shower Cards',
    headlineLead: 'The baby shower card',
    headlineHighlight: 'everyone can join.',
    subline: 'One link. Friends, family and colleagues sign from anywhere — warm messages, photos, voice notes and a pooled baby shower gift. Perfect for virtual showers too.',
    ctaLabel: 'Create Baby Shower Card — Free',
    trustBadges: ['Free to create', 'No account to sign', 'Gift fund included', 'Virtual shower friendly'],
    howItWorksHeading: 'A baby shower card that reaches everyone, in four steps',
    howItWorksSteps: [
      { icon: 'Wand', n: '1', title: 'Create in 90 seconds', desc: 'Choose Baby Shower, pick a beautiful design, set the delivery time. Done before the kettle boils.' },
      { icon: 'Share2', n: '2', title: 'Share one link', desc: 'Send to the WhatsApp group, email chain or Slack. Anyone clicks and adds their message — no account needed.' },
      { icon: 'MessageSquare', n: '3', title: 'Everyone signs', desc: 'Warm messages, photos of past memories, GIFs, voice notes. Remote guests and overseas family included automatically.' },
      { icon: 'Baby', n: '4', title: 'Reveal at the shower', desc: 'Deliver on screen at the party, or privately by email. With the pooled gift total, if contributions were enabled.' },
    ],
    featuresHeading: 'Everything a baby shower card should have',
    featuresSub: 'All included in every plan — no extras, no tiers, no surprises.',
    features: [
      { icon: 'Users', title: 'The whole village signs', desc: 'Colleagues, family, friends abroad — no cap on contributors. Everyone adds their wishes from one link, no account needed.' },
      { icon: 'Mic', title: 'Voice notes from the heart', desc: 'A voice message from a best friend or a grandparent-to-be is something the mum-to-be will replay for years. Included in every card.' },
      { icon: 'Gift', title: 'Baby gift fund built in', desc: 'Enable the optional collection pot. Guests contribute any amount when they sign — no chasing.' },
      { icon: 'Globe', title: 'Virtual shower friendly', desc: 'Can\'t all be in the same room? The link works from any device, anywhere. London, Lagos, New York — all sign the same card.' },
      { icon: 'Clock', title: 'Deliver at the shower itself', desc: 'Schedule delivery for the exact moment the card is revealed — open it on a screen at the shower, or sent privately at any time.' },
      { icon: 'Film', title: 'Memory Movie™ included', desc: 'Every card auto-generates a 1080p MP4 from all messages, photos and voice notes — a keepsake for the new family.' },
    ],
    coverEyebrow: 'Baby shower cover designs',
    coverTitle: 'Choose a cover for the new arrival',
    coverDescription: 'New A4 covers made for baby showers, ready to personalise with messages, photos, voice notes and a group gift.',
    faqs: [
      { q: 'How does an online baby shower card work?', a: 'Create the card in under 2 minutes, share one link with guests, and everyone adds their warm message, photo, GIF or voice note from their phone. Schedule it to be revealed at the shower itself or delivered privately.' },
      { q: 'Can remote and overseas guests sign?', a: 'Yes — the link works from any device, anywhere. Friends in London, family in Lagos, cousins in New York — they all sign the same card from one link with no account needed.' },
      { q: 'How does the baby shower gift fund work?', a: 'Enable the optional gift collection when creating the card. Everyone contributes whatever amount they like when they sign — paid securely by card. The mum-to-be withdraws the total directly to her bank account.' },
      { q: 'Do signers need an account?', a: 'No. Anyone with the link can sign instantly from their phone — no registration, no app download, no password.' },
    ],
    finalCtaLead: 'Celebrate the new arrival',
    finalCtaHighlight: 'with everyone who loves her.',
    finalCtaSub: 'Free to create. The whole group signs. Pooled gift collected automatically.',
  },

  // ── /occasions/wedding ────────────────────────────────────────────────────
  wedding: {
    cardOccasion: 'wedding', coverOccasion: 'wedding',
    seoTitle: 'Wedding Congratulations Group Cards — Sign as a Team, Gift Together | Thankeeu',
    seoDescription: 'Send a beautiful wedding congratulations group card. Everyone on the team or in the family adds their warmest wishes, and you pool a wedding gift in any currency — all in one place.',
    seoKeywords: 'wedding congratulations group card, group wedding gift pool, online wedding card colleagues, team wedding card, wedding congratulations message, wedding gift contribution, congratulations on your wedding, digital wedding card, group wedding ecard, wedding card everyone signs',
    canonical: '/occasions/wedding',
    eyebrow: 'Online Wedding Cards',
    headlineLead: 'Celebrate love',
    headlineHighlight: 'from everyone who matters.',
    subline: 'Family, friends and colleagues all sign one card and pool a wedding gift together — in any currency, with no cash-collection awkwardness.',
    ctaLabel: 'Create Wedding Card — Free',
    trustBadges: ['Free to create', 'No account to sign', 'Gift pool in any currency', 'Works for family abroad'],
    howItWorksHeading: 'A wedding card everyone signs, in four steps',
    howItWorksSteps: STANDARD_STEPS,
    featuresHeading: 'Everything a wedding congratulations card needs',
    featuresSub: 'All included in every card. No extras, no tiers, no surprises.',
    features: [
      { icon: 'CheckCircle', title: 'Personal blessings in their voice', desc: 'A blessing from a parent or grandparent means everything. Voice notes let family record their wishes in their own voice — a keepsake for life.' },
      { icon: 'Gift', title: 'No more gift collection drama', desc: 'The gift pot organises everything — everyone contributes securely online, and the couple sees the total and withdraws it cleanly.' },
      { icon: 'Users', title: 'Works for all wedding styles', desc: 'Civil ceremony, religious wedding, destination celebration or intimate gathering — a Thankeeu card brings everyone together with the right message.' },
      { icon: 'Globe', title: 'Family everywhere can sign', desc: 'Relatives in other countries, friends who can\'t make the journey — they can all sign the card and contribute to the gift from anywhere.' },
      { icon: 'Camera', title: 'Photos, GIFs & voice notes', desc: 'Each signer personalises their message with photos, a GIF, or a voice recording straight from their phone.' },
      { icon: 'Film', title: 'Memory Movie™ included', desc: 'Every card auto-generates a 1080p MP4 movie from all the messages, photos and voice notes — free with every plan.' },
    ],
    coverEyebrow: 'Wedding cover designs',
    coverTitle: 'Choose a cover fit for their big day',
    coverDescription: 'Browse the newest premium wedding covers. Select one to open it in the album studio and add every guest\'s messages, photos, GIFs and voice notes.',
    faqs: [
      { q: 'How do I create a wedding congratulations group card?', a: 'Click "Create a card", choose Wedding, enter the couple\'s details, then share the link via email with family, friends, and colleagues. Everyone signs without needing an account.' },
      { q: 'Can we pool a wedding gift using Thankeeu?', a: 'Yes. The gift pot allows any number of contributors to send any amount. The couple withdraws the total directly to their bank account.' },
      { q: 'Can family members abroad contribute to a wedding gift?', a: 'Yes. Contributors can pay in their local currency. Family anywhere in the world can all contribute to the same wedding gift pot.' },
      { q: 'How many people can sign a wedding congratulations card?', a: 'Unlimited. We have seen wedding cards with 100+ family members, friends, and colleagues all signing together.' },
    ],
    finalCtaLead: 'Give them a wedding card',
    finalCtaHighlight: 'as memorable as the day itself.',
    finalCtaSub: 'Free to create. Everyone signs. Gift pooled in any currency.',
  },

  // ── /cards/maternity-leave ────────────────────────────────────────────────
  'maternity-leave': {
    // Framed as a send-off — maps to the same 'leaving' card-creation flow
    // and cover catalogue, matching the existing copy ("her last day before leave").
    cardOccasion: 'leaving', coverOccasion: 'leaving',
    seoTitle: 'Maternity Leave Card — Group Cards for Mums-to-Be | Thankeeu',
    seoDescription: 'Send a colleague off on maternity leave with a group card the whole team signs — warm wishes, photos, voice notes, and a pooled baby gift.',
    seoKeywords: 'maternity leave card, group maternity card, maternity card for colleague, baby shower card online, good luck maternity leave card, card for colleague going on maternity leave',
    canonical: '/cards/maternity-leave',
    eyebrow: 'Maternity Leave Cards',
    headlineLead: 'Send her off',
    headlineHighlight: 'with love from everyone.',
    subline: 'One card, every colleague, and a pooled gift for the new arrival — delivered on her last day before leave.',
    ctaLabel: 'Create Maternity Card — Free',
    trustBadges: ['Free to create', 'No account to sign', 'Baby gift collection', 'Works for remote colleagues'],
    howItWorksHeading: 'A proper send-off in four steps',
    howItWorksSteps: STANDARD_STEPS,
    featuresHeading: 'Everything a maternity send-off needs',
    featuresSub: 'All included in every card. No extras, no tiers, no surprises.',
    features: STANDARD_FEATURES,
    coverEyebrow: 'Send-off cover designs',
    coverTitle: 'Choose a cover for her send-off',
    coverDescription: 'Browse the newest premium A4 designs. Select one to open it in the album studio and add the team\'s messages, photos, GIFs, videos and voice notes.',
    faqs: [
      { q: 'When should we send a maternity leave card?', a: 'Most teams schedule it for the colleague\'s last working day before leave — Thankeeu delivers it at the exact time you choose.' },
      { q: 'Can we pool money for a baby gift?', a: 'Yes — everyone contributes when they sign, and the pooled gift goes to the parent-to-be.' },
      { q: 'Can people sign without an account?', a: 'Yes — one link, no registration, works on any phone.' },
      { q: 'Can we send another card when the baby arrives?', a: 'Absolutely — many teams send a maternity card at leave and a new baby card after the arrival.' },
    ],
    finalCtaLead: 'Send her off',
    finalCtaHighlight: 'the way she deserves.',
    finalCtaSub: 'Free to create. The whole team signs. Delivered at the exact moment you choose.',
  },

  // ── /online-birthday-cards-nigeria ────────────────────────────────────────
  'birthday-nigeria': {
    cardOccasion: 'birthday', coverOccasion: 'birthday',
    seoTitle: 'Online Birthday Cards Nigeria — Buy, Personalise & Send Same Day | Thankeeu',
    seoDescription: 'Buy an online birthday card in Nigeria — personalised, delivered instantly, signed by everyone who loves them. No printing, no Lagos traffic, no delivery fees. Add a pooled Naira gift via Flutterwave.',
    seoKeywords: 'online birthday card Nigeria, birthday card Lagos, buy birthday card Nigeria, where to buy birthday card in Nigeria, customised birthday card Nigeria, personalised birthday card Nigeria, birthday card delivery Lagos, send birthday card Nigeria, happy birthday card design Nigeria, birthday card for colleague Nigeria, group birthday card Nigeria, birthday card Abuja',
    canonical: '/online-birthday-cards-nigeria',
    eyebrow: 'Online Birthday Cards — Nigeria',
    headlineLead: 'Skip the traffic.',
    headlineHighlight: 'Skip the printing fees.',
    subline: 'Create a beautiful birthday card online, get everyone to sign it, and deliver it at midnight — anywhere in Nigeria, with a pooled Naira gift built in.',
    ctaLabel: 'Create Birthday Card — Free',
    trustBadges: ['Free to create', 'No account to sign', 'Naira gift via Flutterwave', 'Delivered anywhere in Nigeria'],
    howItWorksHeading: 'A birthday card that beats Lagos traffic, in four steps',
    howItWorksSteps: STANDARD_STEPS,
    featuresHeading: 'Everything a Nigerian birthday card needs',
    featuresSub: 'All included in every card. No extras, no tiers, no surprises.',
    features: [
      { icon: 'MapPin', title: 'Delivered anywhere in Nigeria', desc: 'Lagos, Abuja, Port Harcourt, Kano — anywhere with a phone signal. No delivery zones, no courier fees.' },
      { icon: 'Users', title: 'Personalised by everyone', desc: 'Colleagues, family, friends abroad — messages, photos and voice notes from everyone, not just one signature.' },
      { icon: 'Gift', title: 'Naira gift pool via Flutterwave', desc: 'Contributors chip into a secure gift pool when they sign. The celebrant withdraws to any Nigerian bank.' },
      { icon: 'Clock', title: 'Midnight delivery', desc: 'Set the exact date and time — including midnight — and it arrives on the dot, any day of the week.' },
      { icon: 'Camera', title: 'Photos, GIFs & voice notes', desc: 'Each signer personalises their message with photos, a GIF, or a voice recording straight from their phone.' },
      { icon: 'Film', title: 'Memory Movie™ included', desc: 'Every card auto-generates a 1080p MP4 movie from all the messages, photos and voice notes — free with every plan.' },
    ],
    coverEyebrow: 'Birthday cover designs',
    coverTitle: 'Choose a cover worth celebrating',
    coverDescription: 'Browse the newest premium A4 birthday designs. Select one to open it in the album studio and add everyone\'s messages, photos, GIFs and voice notes.',
    faqs: [
      { q: 'Can I send an online birthday card anywhere in Nigeria?', a: 'Yes — Lagos, Abuja, Port Harcourt, Kano, anywhere with a phone signal. The card is delivered by email and viewable on any device, so there are no delivery zones, no courier fees, and no "we don\'t deliver on Sundays."' },
      { q: 'How is this different from buying a physical birthday card?', a: 'A physical card is one design, one or two signatures, delivered by dispatch rider if you\'re lucky. An online group card is personalised by everyone who signs it — messages, photos, voice notes — delivered at the exact moment you choose, and kept forever.' },
      { q: 'Can I customise the design?', a: 'Yes — choose from beautiful designs for every occasion and personality, add a cover photo of the celebrant, and every signer personalises their own message.' },
      { q: 'How much does an online birthday card cost in Nigeria?', a: 'Free to create and collect messages. A small fee, always shown upfront in Naira, applies when you send.' },
    ],
    finalCtaLead: 'Give them a birthday',
    finalCtaHighlight: 'everyone actually shows up for.',
    finalCtaSub: 'Free to create. Everyone signs. Naira gift pooled automatically.',
  },
  // ── /online-group-card ────────────────────────────────────────────────────
  // Generic, any-occasion page — cardOccasion left empty so the CTA goes to
  // a plain /card/new (person picks their own occasion there), and the cover
  // gallery defaults to birthday designs as the most universally recognisable
  // showcase rather than implying this is birthday-only.
  'online-group-card': {
    cardOccasion: '', coverOccasion: 'birthday',
    seoTitle: 'Online Group Card — Everyone Signs Together | Thankeeu',
    seoDescription: 'Create a free online group card that everyone signs. Perfect for birthdays, farewells, retirements, weddings, and more. Share the link — anyone with it can sign from any device. No account needed.',
    seoKeywords: 'online group card, free online group card, digital group card, group card everyone signs, virtual group card, create group card online',
    canonical: '/online-group-card',
    eyebrow: 'Online Group Cards',
    headlineLead: 'One card.',
    headlineHighlight: 'Everyone signs. Any occasion.',
    subline: 'Create a free group card in 2 minutes. Share the link with the whole team, family, or friend group — everyone adds their message, photo, or voice note, and the recipient gets one beautiful card.',
    ctaLabel: 'Create Your Card — Free',
    trustBadges: ['Free to create', 'No account to sign', 'Works for any occasion', 'Gift collection included'],
    howItWorksHeading: 'One link, any occasion, in four steps',
    howItWorksSteps: STANDARD_STEPS,
    featuresHeading: 'Everything a great group card needs',
    featuresSub: 'Works for birthdays, farewells, retirements, anniversaries, weddings, new babies, graduations, promotions, and any occasion worth celebrating together.',
    features: STANDARD_FEATURES,
    coverEyebrow: 'Popular cover designs',
    coverTitle: 'Choose a cover for any occasion',
    coverDescription: 'A taste of the newest designs — browse the full catalogue for every occasion once you start creating.',
    faqs: [
      { q: 'What is an online group card?', a: 'An online group card is a digital card that multiple people sign together for one recipient. Everyone adds their own personal message, photo, or voice note, and the recipient receives it as one beautiful combined card.' },
      { q: 'Is an online group card free?', a: 'Yes — creating your card and inviting people to sign is completely free on Thankeeu. You pay only when sending the final card.' },
      { q: 'How do I invite people to sign an online group card?', a: 'Share the link via WhatsApp, email, Slack, or any messaging app. Anyone with the link can sign from their phone or laptop — no account needed.' },
      { q: 'What occasions work for online group cards?', a: 'Any occasion where a group wants to celebrate someone together: birthdays, farewells, retirements, weddings, anniversaries, new baby, graduation, promotions, and more.' },
      { q: 'Can I add a gift to an online group card?', a: 'Yes. Thankeeu lets you combine a group card with a pooled gift collection — guests sign and contribute to the gift in one flow.' },
    ],
    finalCtaLead: 'One card.',
    finalCtaHighlight: 'Everyone signs. Any occasion.',
    finalCtaSub: 'Free to create. Everyone signs. Delivered at the exact moment you choose.',
  },
};
