// Data-driven config for KeywordLandingPage.jsx — one entry per generic
// high-intent keyword landing page (ecards, virtual cards, etc.), following
// the exact same structural pattern as LeavingCardPage.jsx.
// No emojis anywhere — Icon component only, matching site-wide standard.

export const KEYWORD_PAGES = {

  'ecards': {
    path: '/ecards',
    eyebrow: 'Online eCards - UK, US & Global',
    h1a: 'One eCard.',
    h1b: 'Everyone signs it together.',
    metaTitle: 'Free eCards Online - Group eCards Everyone Signs | Thankeeu',
    metaDescription: 'Create a free eCard the whole group signs from one link. Messages, photos, voice notes and a pooled gift - for birthdays, farewells, retirements and more. No app needed.',
    keywords: 'ecards, free ecards, online ecards, group ecard, ecard maker, send an ecard, ecards for friends, digital card',
    heroSub: 'Most eCards are a single design one person sends. Thankeeu is different - share one link and everyone in the group adds their own message, photo or voice note to the same card before it\'s delivered.',
    priceLabel: 'From $3.15 to send',
    occasionParam: '',
    diffLine: 'Unlike a single-sender eCard - everyone contributes, voice notes included, gift pot built in. Free to create.',
    howItWorks: [
      { icon: 'Wand', title: 'Pick a design', desc: 'Choose from 100+ premium eCard designs for any occasion. Takes under a minute.' },
      { icon: 'Link', title: 'Share one link', desc: 'Send the link by WhatsApp, email or text. No account needed for anyone to sign.' },
      { icon: 'PenLine', title: 'Everyone adds a message', desc: 'Each person writes their own message, adds a photo, or records a voice note.' },
      { icon: 'Send', title: 'Delivered on time', desc: 'Schedule delivery for the exact moment - the recipient opens one card, full of everyone.' },
    ],
    features: [
      { icon: 'Users', title: 'Built for groups, not one sender', desc: 'A normal eCard is one person, one message. Thankeeu lets an entire team, family or friend group sign the same card.' },
      { icon: 'Mic', title: 'Voice notes, not just text', desc: 'Text is easy to skip past. A recorded voice message is something the recipient actually keeps and replays.' },
      { icon: 'Gift', title: 'Gift pot included', desc: 'Collect a group gift contribution alongside the card - no separate payment link or spreadsheet needed.' },
      { icon: 'Film', title: 'Memory Movie included', desc: 'Every message, photo and voice note is automatically turned into a short cinematic video the recipient keeps.' },
      { icon: 'Clock', title: 'Scheduled delivery', desc: 'Set the exact date and time. The card arrives precisely when it should, not whenever someone remembers to send it.' },
      { icon: 'Globe', title: 'Works anywhere in the world', desc: 'Multi-currency gift collection and no app requirement means it works the same for a group spread across countries.' },
    ],
    comparisonRows: [
      { feature: 'Multiple people sign one card', other: false, us: true },
      { feature: 'Voice note messages', other: false, us: true },
      { feature: 'Gift collection built in', other: false, us: true },
      { feature: 'Auto-generated Memory Movie', other: false, us: true },
      { feature: 'No account needed to sign', other: true, us: true },
      { feature: 'Free to create', other: true, us: true },
    ],
    faqs: [
      { q: 'What is an eCard?', a: 'An eCard (electronic card) is a digital greeting card sent online instead of printed and mailed. Most eCards are designed and sent by one person to one recipient. Thankeeu is a group eCard - instead of one sender, an entire group of people each add their own message, photo or voice note to the same card before it is delivered.' },
      { q: 'Is Thankeeu really free?', a: 'Yes. Creating the card, choosing a design, and collecting messages from your group costs nothing. A small one-time fee applies only when you are ready to send the finished card - from $3.15 USD.' },
      { q: 'Do people need to download an app to sign?', a: 'No. Everyone signs directly from the link in their browser - no app download, no account, no password. Works on any phone, tablet or computer.' },
      { q: 'Can I add a group gift to the eCard?', a: 'Yes. Enable gift collection when you create the card and each signer can contribute alongside their message, in their own currency.' },
      { q: 'What occasions can I use this for?', a: 'Birthdays, farewells, retirements, weddings, work anniversaries, get well soon, thank you, sympathy and more. Any moment where a group wants to say something together.' },
    ],
    relatedLinks: [
      { to: '/virtual-cards', label: 'Virtual Cards' },
      { to: '/cards/leaving-card', label: 'Online Leaving Cards' },
      { to: '/occasions/birthday', label: 'Birthday Group Cards' },
      { to: '/pricing', label: 'Pricing' },
    ],
  },

  'free-ecards-for-friends-and-family': {
    path: '/free-ecards-for-friends-and-family',
    eyebrow: 'Free eCards for Friends & Family',
    h1a: 'Free to make.',
    h1b: 'Better when everyone joins in.',
    metaTitle: 'Free eCards for Friends and Family - Group Cards Everyone Signs | Thankeeu',
    metaDescription: 'Send a free eCard to a friend or family member that the whole group can sign. Messages, photos and voice notes from everyone who cares, in one card. Free to create.',
    keywords: 'free ecards for friends, free ecards for family, ecards for friends and family, free online cards, group card for family, send free card online',
    heroSub: 'A single "thinking of you" text gets forgotten. A card that the whole friend group or family signed together, with real messages and photos, does not.',
    priceLabel: 'Free to start',
    occasionParam: '',
    diffLine: 'Unlike a card from one person - collect messages from the whole friend group or family, free.',
    howItWorks: [
      { icon: 'Wand', title: 'Choose who it is for', desc: 'Pick the occasion and a design that fits - birthday, get well soon, thinking of you, and more.' },
      { icon: 'Share2', title: 'Invite the group', desc: 'Send the link to everyone who wants to add something - siblings, cousins, old friends, anyone.' },
      { icon: 'Heart', title: 'Everyone adds their bit', desc: 'Messages, photos, even a short voice note - each person contributes in their own way.' },
      { icon: 'Send', title: 'Send when ready', desc: 'Deliver it instantly or schedule it for a specific date, like their actual birthday.' },
    ],
    features: [
      { icon: 'Users', title: 'The whole family, one card', desc: 'Instead of ten separate texts, everyone signs the same card - it reads like a proper collective gesture, not scattered messages.' },
      { icon: 'Camera', title: 'Old photos welcome', desc: 'Attach a photo from years ago alongside your message - the kind of thing that makes a card genuinely emotional.' },
      { icon: 'Mic', title: 'A voice, not just words', desc: 'Record a 30-second voice note instead of typing. Hearing someone\'s actual voice means more than any text.' },
      { icon: 'Gift', title: 'Chip in for a gift too', desc: 'If the group wants to also send money or a gift, collect contributions in the same place - no separate app.' },
      { icon: 'Film', title: 'A movie they will keep', desc: 'Everything gets automatically turned into a short video montage - something to watch again on future birthdays.' },
      { icon: 'Smile', title: 'No awkward sign-up', desc: 'Nobody needs an account. Click the link, write your message, done - takes less time than finding a card at a shop.' },
    ],
    comparisonRows: [
      { feature: 'Free to create the card', other: true, us: true },
      { feature: 'Whole family/group can sign', other: false, us: true },
      { feature: 'Voice note messages', other: false, us: true },
      { feature: 'Photo attachments per message', other: false, us: true },
      { feature: 'Optional group gift collection', other: false, us: true },
    ],
    faqs: [
      { q: 'Is it actually free?', a: 'Yes - creating the card and collecting messages from your friends and family costs nothing. You only pay a small fee if you choose to add the card to a paid delivery plan; the Classic single-card option starts at $3.15.' },
      { q: 'How many people can sign the card?', a: 'As many as you invite. There is no cap on the number of signers for a group card.' },
      { q: 'Can family members overseas sign too?', a: 'Yes. Anyone with the link can sign from anywhere in the world, on any device, in their own currency for gift contributions.' },
      { q: 'What if someone is not tech-savvy?', a: 'The signing process is deliberately simple - open the link, type a message, tap send. No accounts, no downloads, no confusing steps.' },
    ],
    relatedLinks: [
      { to: '/ecards', label: 'eCards' },
      { to: '/occasions/birthday', label: 'Birthday Cards' },
      { to: '/virtual-cards', label: 'Virtual Cards' },
      { to: '/pricing', label: 'Pricing' },
    ],
  },

  'virtual-cards': {
    path: '/virtual-cards',
    eyebrow: 'Virtual Cards for Every Occasion',
    h1a: 'A virtual card',
    h1b: 'signed by everyone, not just you.',
    metaTitle: 'Virtual Cards for Every Occasion - Group Signing | Thankeeu',
    metaDescription: 'Create a virtual card the whole group signs from one link. Birthdays, farewells, weddings and more - messages, photos, voice notes and a gift pot, all in one place.',
    keywords: 'virtual cards, virtual greeting cards, virtual card maker, send virtual card, virtual birthday card, virtual group card',
    heroSub: 'A virtual card usually means one design from one sender. Thankeeu turns it into a shared experience - one link, and everyone who wants to be part of it adds their own message.',
    priceLabel: 'From $3.15 to send',
    occasionParam: '',
    diffLine: 'Unlike a typical virtual card - built for groups, with voice notes and a gift pot included.',
    howItWorks: [
      { icon: 'Palette', title: 'Pick a card design', desc: 'Choose from a wide range of virtual card designs across every occasion.' },
      { icon: 'Link', title: 'Share the link', desc: 'One link goes to everyone who should be part of the card - by text, email or WhatsApp.' },
      { icon: 'MessagesSquare', title: 'Collect every message', desc: 'Each person signs with their own message, photo, or a short voice recording.' },
      { icon: 'CalendarClock', title: 'Deliver on schedule', desc: 'Send it instantly, or set it to arrive automatically at the perfect moment.' },
    ],
    features: [
      { icon: 'Users', title: 'A shared virtual card, not a solo one', desc: 'Most virtual cards are built for one sender. Thankeeu is built so a whole team, family or friend group can contribute to the same card.' },
      { icon: 'Mic', title: 'Voice messages included', desc: 'Beyond text and photos, signers can leave a recorded voice message - a detail most virtual card tools skip entirely.' },
      { icon: 'Gift', title: 'Collect a gift at the same time', desc: 'Enable gift collection so the group can also contribute money toward a present, alongside their messages.' },
      { icon: 'Film', title: 'Turns into a Memory Movie', desc: 'All the messages, photos and voice notes are automatically compiled into a short video the recipient can watch and keep.' },
      { icon: 'ShieldCheck', title: 'No account required for signers', desc: 'Anyone with the link can add their message straight away - no sign-up, no password, no friction.' },
      { icon: 'Globe2', title: 'Multi-currency support', desc: 'Gift contributions work across currencies, so groups spread across different countries can all take part.' },
    ],
    comparisonRows: [
      { feature: 'Multiple signers per card', other: false, us: true },
      { feature: 'Voice note messages', other: false, us: true },
      { feature: 'Gift collection built in', other: false, us: true },
      { feature: 'Automatic video montage', other: false, us: true },
      { feature: 'No signup required to sign', other: true, us: true },
    ],
    faqs: [
      { q: 'What is a virtual card?', a: 'A virtual card is a digital greeting card sent online instead of a physical, printed card. Thankeeu\'s version is collaborative - instead of a card from one sender, a whole group signs the same card together via a shared link.' },
      { q: 'How much does it cost?', a: 'Creating the card and collecting signatures is free. A small one-time fee applies when you are ready to send, starting from $3.15 USD.' },
      { q: 'Can I include a gift with the virtual card?', a: 'Yes. Turn on gift collection when creating the card, and signers can contribute toward a gift in the same place they leave their message.' },
      { q: 'Does the recipient need an app to open it?', a: 'No. The card opens directly in any web browser on any device, with no app or account required.' },
    ],
    relatedLinks: [
      { to: '/virtual-birthday-card', label: 'Virtual Birthday Card' },
      { to: '/ecards', label: 'eCards' },
      { to: '/cards/leaving-card', label: 'Online Leaving Cards' },
      { to: '/pricing', label: 'Pricing' },
    ],
  },

  'virtual-birthday-card': {
    path: '/virtual-birthday-card',
    eyebrow: 'Virtual Birthday Cards - Group Signing',
    h1a: 'One birthday card.',
    h1b: 'Every message, one link.',
    metaTitle: 'Virtual Birthday Card - Everyone Signs From One Link | Thankeeu',
    metaDescription: 'Send a virtual birthday card the whole group signs together. Messages, photos, voice notes and a pooled birthday gift - delivered right on their birthday.',
    keywords: 'virtual birthday card, online birthday card, group birthday card, birthday ecard, birthday card everyone signs, virtual card for birthday',
    heroSub: 'Instead of a single "happy birthday" text, gather everyone into one virtual card - messages, old photos, voice notes, all delivered together on the day.',
    priceLabel: 'From $3.15 to send',
    occasionParam: '?occasion=birthday',
    diffLine: 'Unlike a solo birthday text - the whole group contributes, with a gift pot built in.',
    howItWorks: [
      { icon: 'Cake', title: 'Pick a birthday design', desc: 'Choose from dozens of birthday-specific card designs and colour themes.' },
      { icon: 'Link', title: 'Invite the group', desc: 'Share the link with everyone who wants to wish them happy birthday.' },
      { icon: 'PenLine', title: 'Collect every wish', desc: 'Each person adds their message, a photo, or a short voice recording.' },
      { icon: 'CalendarClock', title: 'Deliver on their birthday', desc: 'Schedule it to arrive at exactly the right moment on the day itself.' },
    ],
    features: [
      { icon: 'Users', title: 'The whole friend group, one card', desc: 'Instead of a dozen separate birthday texts, every wish lands in one card the birthday person actually keeps.' },
      { icon: 'Gift', title: 'Birthday gift pot included', desc: 'Collect contributions toward a birthday gift alongside the messages - no separate Venmo request needed.' },
      { icon: 'Mic', title: 'Voice birthday wishes', desc: 'A recorded "happy birthday" in someone\'s actual voice means far more than a typed message.' },
      { icon: 'Film', title: 'Auto Birthday Memory Movie', desc: 'Every message and photo becomes a short cinematic video - a birthday keepsake they will watch again next year.' },
      { icon: 'CalendarClock', title: 'Scheduled for the actual day', desc: 'Set delivery for their exact birthday, so it lands at the right moment instead of days early or late.' },
      { icon: 'Smile', title: 'No account needed to sign', desc: 'Anyone can add their birthday message straight from the link - no downloads, no sign-up.' },
    ],
    comparisonRows: [
      { feature: 'Whole group can sign one card', other: false, us: true },
      { feature: 'Voice birthday messages', other: false, us: true },
      { feature: 'Birthday gift pot included', other: false, us: true },
      { feature: 'Scheduled delivery on the day', other: true, us: true },
      { feature: 'Auto-generated video montage', other: false, us: true },
    ],
    faqs: [
      { q: 'Can I schedule the card for their exact birthday?', a: 'Yes. Set the delivery date and time when creating the card, and it arrives automatically on the day - no need to remember to send it yourself.' },
      { q: 'How many people can add a birthday message?', a: 'There is no limit. Invite as many friends, family members or colleagues as you like.' },
      { q: 'Can we include a birthday gift?', a: 'Yes, enable gift collection and everyone who signs can also contribute toward a gift, in their own currency.' },
      { q: 'Is it free to create?', a: 'Yes, creating the card and collecting birthday messages is free. A small fee applies only when you send the finished card, from $3.15.' },
    ],
    relatedLinks: [
      { to: '/occasions/birthday', label: 'Birthday Group Cards' },
      { to: '/virtual-cards', label: 'Virtual Cards' },
      { to: '/ecards', label: 'eCards' },
      { to: '/pricing', label: 'Pricing' },
    ],
  },

  'group-ecard': {
    path: '/group-ecard',
    eyebrow: 'Group eCards - Everyone Signs One Card',
    h1a: 'A group eCard.',
    h1b: 'Made by everyone, for one person.',
    metaTitle: 'Group eCard - Everyone Signs the Same Card | Thankeeu',
    metaDescription: 'Create a group eCard where the whole team, family or friend group signs the same card from one link. Messages, photos, voice notes and a gift, delivered together.',
    keywords: 'group ecard, group ecard for coworker, group ecard maker, group ecard online, ecard for group, collaborative ecard',
    heroSub: 'A group eCard is one shared card that multiple people sign together - instead of everyone sending their own message separately.',
    priceLabel: 'From $3.15 to send',
    occasionParam: '',
    diffLine: 'Unlike sending separate messages - collect everyone in one link, one card, one delivery.',
    howItWorks: [
      { icon: 'Wand', title: 'Set up the card', desc: 'Choose an occasion and design - takes about two minutes.' },
      { icon: 'Share2', title: 'Send one link to the group', desc: 'Share it in a group chat, over email, or however your group communicates.' },
      { icon: 'Users', title: 'Everyone signs in', desc: 'Each person adds their own message, photo or voice note, in their own time.' },
      { icon: 'Send', title: 'One card, delivered', desc: 'The recipient gets a single, complete card with everyone\'s contribution inside.' },
    ],
    features: [
      { icon: 'Users', title: 'Built specifically for groups', desc: 'This is not a card meant for one sender - it is designed from the ground up for teams, families and friend groups to sign together.' },
      { icon: 'Clock', title: 'Signers can add their message anytime', desc: 'No need to coordinate everyone at once - people sign whenever suits them before the delivery date.' },
      { icon: 'Mic', title: 'Voice, photo and text all supported', desc: 'Each contributor picks how they want to say it - typed message, photo, or a recorded voice note.' },
      { icon: 'Gift', title: 'Group gift collection', desc: 'Alongside messages, the group can also pool money toward a gift - all in the same link.' },
      { icon: 'Lock', title: 'Private until delivery', desc: 'Signers cannot see each other\'s messages unless you choose to make them visible - keeping surprises intact.' },
      { icon: 'Globe', title: 'Works for remote and global groups', desc: 'No matter where each signer is in the world, they can contribute from any device with a browser.' },
    ],
    comparisonRows: [
      { feature: 'Multiple signers, one card', other: true, us: true },
      { feature: 'Voice note messages', other: false, us: true },
      { feature: 'Group gift collection built in', other: false, us: true },
      { feature: 'No account needed to sign', other: true, us: true },
      { feature: 'Auto-generated Memory Movie', other: false, us: true },
    ],
    faqs: [
      { q: 'What exactly is a group eCard?', a: 'It is a single digital card that multiple people sign together via a shared link, instead of one person designing and sending a card alone. Everyone\'s message ends up in the same finished card.' },
      { q: 'How do people sign it?', a: 'Each signer opens the link, writes their message (or adds a photo or voice note), and submits it. No account or app is required.' },
      { q: 'Can I see who has signed so far?', a: 'Yes, the card creator can see how many people have signed and a live count as messages come in.' },
      { q: 'Can we add a gift contribution?', a: 'Yes, enable gift collection and signers can contribute toward a group gift alongside their message.' },
    ],
    relatedLinks: [
      { to: '/ecard-for-coworker', label: 'eCard for a Coworker' },
      { to: '/ecards', label: 'eCards' },
      { to: '/cards/leaving-card', label: 'Leaving Cards' },
      { to: '/pricing', label: 'Pricing' },
    ],
  },

  'digital-greeting-cards': {
    path: '/digital-greeting-cards',
    eyebrow: 'Digital Greeting Cards - Group Edition',
    h1a: 'A digital greeting card',
    h1b: 'that more than one person can sign.',
    metaTitle: 'Digital Greeting Cards Everyone Can Sign | Thankeeu',
    metaDescription: 'Create a digital greeting card the whole group signs from one link. Messages, photos, voice notes and a pooled gift - for any occasion, delivered on schedule.',
    keywords: 'digital greeting cards, digital greeting card maker, online greeting cards, digital card for group, send digital greeting card, group greeting card',
    heroSub: 'Most digital greeting card tools are built for one sender. Thankeeu is built for the group - one shared card that everyone contributes to.',
    priceLabel: 'From $3.15 to send',
    occasionParam: '',
    diffLine: 'Unlike a typical digital greeting card - collaborative by design, gift pot included, free to start.',
    howItWorks: [
      { icon: 'Palette', title: 'Choose a greeting card design', desc: 'Pick from a wide range of digital greeting card templates across every occasion.' },
      { icon: 'Link', title: 'Share the signing link', desc: 'Send it to everyone you want to include - no printing, no mailing.' },
      { icon: 'PenLine', title: 'Collect messages', desc: 'Everyone adds their own greeting - text, photo, or a recorded voice message.' },
      { icon: 'CalendarClock', title: 'Send or schedule delivery', desc: 'Deliver the finished card instantly or set it to arrive at a specific time.' },
    ],
    features: [
      { icon: 'Users', title: 'Group-signed, not single-sender', desc: 'A regular digital greeting card comes from one person. Thankeeu lets an entire group add their own greeting to the same card.' },
      { icon: 'Mic', title: 'Voice greetings included', desc: 'Beyond text, signers can record a short voice message - something far more personal than typed words.' },
      { icon: 'Gift', title: 'Gift collection alongside the card', desc: 'Collect a group gift contribution in the same link, without a separate payment tool.' },
      { icon: 'Film', title: 'Turns into a video keepsake', desc: 'Every message and photo is automatically compiled into a short Memory Movie the recipient keeps.' },
      { icon: 'Leaf', title: 'No printing or postage', desc: 'Fully digital, delivered instantly or on a schedule - no envelopes, no stamps, no delays.' },
      { icon: 'ShieldCheck', title: 'No account needed for signers', desc: 'Anyone with the link can add their greeting straight away, on any device.' },
    ],
    comparisonRows: [
      { feature: 'Multiple people sign one card', other: false, us: true },
      { feature: 'Voice message greetings', other: false, us: true },
      { feature: 'Gift collection built in', other: false, us: true },
      { feature: 'Scheduled delivery', other: true, us: true },
      { feature: 'Free to create', other: true, us: true },
    ],
    faqs: [
      { q: 'How is this different from a normal digital greeting card?', a: 'A normal digital greeting card is designed and sent by one person. Thankeeu is a shared, collaborative card - a whole group of people each add their own greeting to the same card before it is delivered.' },
      { q: 'Do I need to design the card myself?', a: 'No, choose from a library of premium designs across every occasion - no design skills needed.' },
      { q: 'Can the card include a gift?', a: 'Yes. Enable gift collection so signers can contribute toward a gift alongside their message.' },
      { q: 'Is there a limit on how many people can sign?', a: 'No, invite as many people as you like to add their greeting to the card.' },
    ],
    relatedLinks: [
      { to: '/ecards', label: 'eCards' },
      { to: '/group-ecard', label: 'Group eCard' },
      { to: '/virtual-cards', label: 'Virtual Cards' },
      { to: '/pricing', label: 'Pricing' },
    ],
  },

  'ecard-for-coworker': {
    path: '/ecard-for-coworker',
    eyebrow: 'eCards for Coworkers - Everyone in the Office Signs',
    h1a: 'An eCard for a coworker',
    h1b: 'the whole office signs together.',
    metaTitle: 'eCard for a Coworker - Group Signed, No App Needed | Thankeeu',
    metaDescription: 'Send an eCard to a coworker that the whole office or team can sign. Messages, photos, voice notes and an optional gift collection, all in one link.',
    keywords: 'ecard for coworker, group card for coworker, office ecard, ecard for colleague, virtual card for coworker, ecard for work',
    heroSub: 'A colleague leaving, celebrating a birthday, or hitting a work anniversary deserves more than one manager\'s email. Get the whole office to sign one card.',
    priceLabel: 'From $3.15 to send',
    occasionParam: '?occasion=leaving',
    diffLine: 'Unlike a card from one manager - the whole office contributes, with a work gift pot included.',
    howItWorks: [
      { icon: 'Wand', title: 'Pick the occasion', desc: 'Leaving, birthday, work anniversary, promotion, or a general thank you.' },
      { icon: 'Link', title: 'Share in the team channel', desc: 'Drop the link in Slack, Teams, or email - no app installation needed for anyone.' },
      { icon: 'Users', title: 'Colleagues sign in', desc: 'Everyone adds their own message, at their own pace, before the deadline.' },
      { icon: 'Send', title: 'Deliver at the right moment', desc: 'Send it on their last day, birthday, or whenever the moment calls for it.' },
    ],
    features: [
      { icon: 'Building2', title: 'Built for office-wide participation', desc: 'Instead of a card only close colleagues sign, get contributions from the whole office, remote team included.' },
      { icon: 'Gift', title: 'Work gift pot included', desc: 'Collect contributions toward a leaving or birthday gift alongside messages, without a separate collection spreadsheet.' },
      { icon: 'Mic', title: 'Voice messages from the team', desc: 'A short recorded message often lands better than another typed paragraph in a work card.' },
      { icon: 'Globe2', title: 'Works for remote and hybrid teams', desc: 'Colleagues working from anywhere can sign from their own device, no office presence required.' },
      { icon: 'ShieldCheck', title: 'No account needed to sign', desc: 'Coworkers click the link and sign immediately - no extra login for a company tool.' },
      { icon: 'Film', title: 'A keepsake video, not just a card', desc: 'Messages and photos are automatically compiled into a short video the colleague can keep.' },
    ],
    comparisonRows: [
      { feature: 'Whole office/team can sign', other: false, us: true },
      { feature: 'Voice note messages', other: false, us: true },
      { feature: 'Work gift pot built in', other: false, us: true },
      { feature: 'Works for remote teams', other: true, us: true },
      { feature: 'No account needed to sign', other: true, us: true },
    ],
    faqs: [
      { q: 'Can remote colleagues sign too?', a: 'Yes, anyone with the link can sign from any device, anywhere - no need to be in the office.' },
      { q: 'Can we collect money for a leaving gift?', a: 'Yes, enable gift collection and colleagues can contribute toward a gift alongside their message, in their own currency.' },
      { q: 'How do we share the card at work?', a: 'Drop the link in your team Slack, Microsoft Teams channel, or send it directly by email - no company software integration required.' },
      { q: 'What occasions does this work for?', a: 'Leaving, birthdays, work anniversaries, promotions, welcoming a new hire, get well soon, or a general thank you to a colleague.' },
    ],
    relatedLinks: [
      { to: '/cards/leaving-card', label: 'Online Leaving Cards' },
      { to: '/group-ecard', label: 'Group eCard' },
      { to: '/occasions/birthday', label: 'Birthday Cards' },
      { to: '/pricing', label: 'Pricing' },
    ],
  },

  'virtual-farewell-card': {
    path: '/virtual-farewell-card',
    eyebrow: 'Virtual Farewell Cards - Group Signing',
    h1a: 'A virtual farewell card',
    h1b: 'signed by everyone who will miss them.',
    metaTitle: 'Virtual Farewell Card - Group Signed Goodbye | Thankeeu',
    metaDescription: 'Create a virtual farewell card the whole team signs from one link. Messages, photos, voice notes and a farewell gift pot - delivered on their last day.',
    keywords: 'virtual farewell card, farewell ecard, online farewell card, group farewell card, farewell card for colleague, virtual goodbye card',
    heroSub: 'A proper goodbye deserves more than a single email. Get the whole team into one virtual farewell card, full of real messages and photos.',
    priceLabel: 'From $3.15 to send',
    occasionParam: '?occasion=leaving',
    diffLine: 'Unlike a single farewell message - the whole team contributes, with a farewell gift pot included.',
    howItWorks: [
      { icon: 'Wand', title: 'Pick a farewell design', desc: 'Choose from designs built specifically for goodbyes and leaving moments.' },
      { icon: 'Link', title: 'Share with the team', desc: 'Send the link to everyone who wants to say goodbye - no app needed.' },
      { icon: 'MessagesSquare', title: 'Collect every goodbye', desc: 'Each colleague adds a message, photo, or a short voice recording.' },
      { icon: 'Send', title: 'Deliver on their last day', desc: 'Schedule the card to arrive at exactly the right moment - their final day.' },
    ],
    features: [
      { icon: 'Users', title: 'The whole team, one goodbye', desc: 'Instead of scattered farewell messages, everything lands in one card that genuinely reflects how the team feels.' },
      { icon: 'Gift', title: 'Farewell gift pot included', desc: 'Collect contributions toward a leaving gift alongside the messages, in one place.' },
      { icon: 'Mic', title: 'Voice farewell messages', desc: 'A recorded goodbye in someone\'s own voice carries more weight than a typed line.' },
      { icon: 'Film', title: 'A farewell keepsake video', desc: 'Every message and photo automatically becomes a short video montage - something worth keeping.' },
      { icon: 'CalendarClock', title: 'Timed for their last day', desc: 'Schedule delivery precisely for their final day, so it lands at the right moment.' },
      { icon: 'Globe2', title: 'Includes remote colleagues', desc: 'Team members working from anywhere can add their goodbye from any device.' },
    ],
    comparisonRows: [
      { feature: 'Whole team can sign', other: false, us: true },
      { feature: 'Voice farewell messages', other: false, us: true },
      { feature: 'Farewell gift pot included', other: false, us: true },
      { feature: 'Scheduled for last day', other: true, us: true },
      { feature: 'Auto-generated keepsake video', other: false, us: true },
    ],
    faqs: [
      { q: 'Can we schedule it for their exact last day?', a: 'Yes, set the delivery date and time when creating the card so it arrives precisely on their final day.' },
      { q: 'Can remote team members sign too?', a: 'Yes, anyone with the link can add their farewell message from anywhere, on any device.' },
      { q: 'Can we collect a leaving gift alongside the card?', a: 'Yes, enable gift collection and colleagues can contribute toward a leaving gift when they sign.' },
      { q: 'Is it free to set up?', a: 'Yes, creating the card and collecting farewell messages is free. A small fee applies only when sending the finished card, from $3.15.' },
    ],
    relatedLinks: [
      { to: '/cards/leaving-card', label: 'Online Leaving Cards' },
      { to: '/ecard-for-coworker', label: 'eCard for a Coworker' },
      { to: '/blog/what-to-write-in-a-leaving-card', label: 'Leaving Card Messages' },
      { to: '/pricing', label: 'Pricing' },
    ],
  },

};

export const KEYWORD_SLUGS = Object.keys(KEYWORD_PAGES);
