import { isValidElement } from 'react';
import {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Ban,
  Banknote,
  BellRing,
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  CalendarDays,
  Camera,
  BarChart3,
  Check,
  Circle,
  AlertCircle,
  CheckCircle,
  XCircle,
  ClipboardCheck,
  Clock3,
  Cloud,
  CloudRain,
  Compass,
  Construction,
  CreditCard,
  File,
  FileEdit,
  Files,
  Flame,
  FolderOpen,
  Footprints,
  Globe2,
  GraduationCap,
  HardHat,
  Heart,
  HeartHandshake,
  Home,
  Stethoscope,
  Contact,
  Image,
  KeyRound,
  Landmark,
  Leaf,
  Lightbulb,
  Loader2,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Microscope,
  Package,
  Paperclip,
  PartyPopper,
  PenLine,
  Phone,
  Pill,
  Plug,
  Printer,
  RadioTower,
  Receipt,
  RefreshCw,
  Rocket,
  Save,
  Scale,
  ScanSearch,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Store,
  Sun,
  Target,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  AlertTriangle,
  Trophy,
  Truck,
  Upload,
  User,
  Users,
  Video,
  Wallet,
  Wifi,
  Wrench,
  X,
  Zap,
} from 'lucide-react';

const rules = [
  [/previous|back|return/, ArrowLeft],
  [/next|continue|view all|details|get started|sign in/, ArrowRight],
  [/warning|danger|unsafe|emergency|alert|nearly exhausted|insufficient/, AlertTriangle],
  [/reject|failed|failure|never|not needed|optional|delete/, XCircle],
  [/complete|completed|approved|verified|mandatory|success|funded|always do|account verified/, CheckCircle],
  [/pending|saving|loading|wait|time|sla|recent/, Clock3],
  [/search|find|inspect|verification|skimming|mystery/, Search],
  [/camera|photo|proof|selfie|picture/, Camera],
  [/video|meeting/, Video],
  [/map|route|location|gps|state|country|coverage|waypoint/, MapPin],
  [/world|global|africa|domain/, Globe2],
  [/bank|atm|finance|fintech/, Landmark],
  [/payment|card|wallet|budget|price|cost|spend|payout|money|fund/, CreditCard],
  [/receipt|invoice/, Receipt],
  [/shop|grocery|market|retail|store|equipment/, ShoppingCart],
  [/delivery|dispatch|courier|logistics|pickup|in transit/, Truck],
  [/package|parcel|file archive/, Package],
  [/document|attachment|file|brief|letter|policy|terms/, File],
  [/edit|write|draft|blog|note/, FileEdit],
  [/folder|history/, FolderOpen],
  [/upload|submit/, Upload],
  [/download|save/, Save],
  [/message|chat|communicate|broadcast/, MessageCircle],
  [/email|mail/, Mail],
  [/phone|mobile|app|telecom/, Smartphone],
  [/team|people|members|company size/, Users],
  [/profile|person|requester|tasker|member/, User],
  [/business|company|office|department|property|building|warehouse|industry/, Building2],
  [/home|residential|family/, Home],
  [/health|hospital|medical|medicine|pharmacy/, Stethoscope],
  [/safety|security|protect|insurance|escrow|lock|compliance/, ShieldCheck],
  [/identity|kyc|nin|bvn/, Contact],
  [/construction|site|tower|ppe|hard hat/, HardHat],
  [/tool|repair|installation|maintenance/, Wrench],
  [/power|electric|urgent|live|fast/, Zap],
  [/target|goal|brand/, Target],
  [/calendar|date|schedule|commencement|duration/, CalendarDays],
  [/report|analytics|views|audit/, BarChart3],
  [/award|badge|enterprise|certif/, Trophy],
  [/learn|read|module|book|guide/, BookOpen],
  [/idea|tip|preview/, Lightbulb],
  [/settings|configure/, Settings],
  [/refresh|ongoing|repeat/, RefreshCw],
  [/launch|rocket/, Rocket],
  [/celebrat|issued|created/, PartyPopper],
  [/heart|care|welfare|support/, HeartHandshake],
  [/like|thumbs up/, ThumbsUp],
  [/dislike|thumbs down/, ThumbsDown],
  [/accessib/, Accessibility],
  [/print/, Printer],
  [/attachment|paperclip/, Paperclip],
  [/send/, Send],
  [/notification|bell/, BellRing],
  [/bot|automation/, Bot],
  [/graduat|career/, GraduationCap],
  [/microscope|research/, Microscope],
  [/fire/, Flame],
  [/weather|sun|outdoor/, Sun],
  [/rain|flood|wet/, CloudRain],
  [/farm|rural|environment/, Leaf],
  [/internet|network|wifi/, Wifi],
  [/plug|fiber/, Plug],
  [/radio|telecom tower/, RadioTower],
  [/key|login|password/, KeyRound],
  [/ban|blacklist/, Ban],
  [/clipboard|task|pledge|checklist/, ClipboardCheck],
  [/handshake|introduction/, HeartHandshake],
  [/shopping|gift/, ShoppingBag],
  [/phone/, Phone],
  [/smile|reaction/, Smile],
];

export function inferIcon(text = '') {
  const searchable = String(text).toLowerCase();
  const match = rules.find(([pattern]) => pattern.test(searchable));
  return match?.[1] || Sparkles;
}

export default function StandardIcon({
  name,
  label,
  size = 20,
  strokeWidth = 1.8,
  className,
  style,
  title,
}) {
  if (isValidElement(name)) return name;

  const Icon = inferIcon(`${name || ''} ${label || ''}`);
  return (
    <Icon
      aria-hidden={title ? undefined : 'true'}
      aria-label={title}
      className={className}
      size={size}
      strokeWidth={strokeWidth}
      style={style}
    />
  );
}

export const iconComponents = {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Ban,
  Banknote,
  Briefcase,
  Building2,
  CalendarDays,
  Camera,
  Check,
  Circle,
  AlertCircle,
  CheckCircle,
  XCircle,
  Clock3,
  Cloud,
  Compass,
  Construction,
  CreditCard,
  File,
  Files,
  Globe2,
  Heart,
  Image,
  Loader2,
  Lock,
  Map,
  Megaphone,
  PenLine,
  Pill,
  ScanSearch,
  Scale,
  Shield,
  ShoppingBag,
  Store,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  X,
};
