// GENERATED from frontend/public/cards/illustrated — do not edit by hand.
// Regenerate with the gen_registry script if covers are added or re-ordered.
// Row: [folder, file stem, occasion id, sympathy group, headline, tagline, background]
// Order per occasion: the first row (4) is the curated cartoon lead; after that
// each row of 4 mixes 2 existing covers with 2 of the newer styles (seeded shuffle).
export const ILLUSTRATED_COVER_ROWS = [
  ["birthday", "b1-cake", "birthday", null, "Happy birthday!", "Make a wish (or three)", "#FFF3DC"],
  ["birthday", "2a-cake", "birthday", null, "Happy Birthday!", "", "#5A499C"],
  ["birthday", "b2-balloons", "birthday", null, "Hip hip hooray!", "It’s your big day!", "#E6DEFA"],
  ["birthday", "b3-gift", "birthday", null, "Surprise!", "Happy birthday, you legend", "#5A499C"],
  ["birthday", "mc-bd2-balloons", "birthday", null, "Up, up & away!", "HAPPY BIRTHDAY", "#E6ECEF"],
  ["birthday", "ad-bd2-rocket", "birthday", null, "Another lap around the sun", "HAPPY BIRTHDAY", "#1F2A44"],
  ["birthday", "b5-party-hat", "birthday", null, "Let’s party!", "Happy birthday!", "#FBCFDF"],
  ["birthday", "bd3-crown", "birthday", null, "Birthday royalty", "Rule the day!", "#5A499C"],
  ["birthday", "ar-bd3-watercolour-wreath", "birthday", null, "Happy Birthday", "TO YOU", "#FBF8F2"],
  ["birthday", "b10-birthday-star", "birthday", null, "Birthday superstar!", "Shine bright today", "#5A499C"],
  ["birthday", "mc-bd10-cheers", "birthday", null, "Cheers to you", "HAPPY BIRTHDAY", "#3C5A80"],
  ["birthday", "2b-balloons", "birthday", null, "Hooray!", "It’s your day!", "#FFF3DC"],
  ["birthday", "ad-bd7-surf", "birthday", null, "Ride the good vibes", "HAPPY BIRTHDAY", "#F4F1EA"],
  ["birthday", "ar-bd10-watercolour-corners", "birthday", null, "Have the best day", "", "#FBF8F2"],
  ["birthday", "b4-cupcake", "birthday", null, "Sweet as a cupcake", "Have the sweetest birthday", "#D6F5EA"],
  ["birthday", "bd2-presents", "birthday", null, "Gifts galore!", "Happy birthday, you!", "#FFF3DC"],
  ["birthday", "b6-donut", "birthday", null, "Donut worry, be happy", "Happy birthday!", "#FFF3DC"],
  ["birthday", "mc-bd9-party", "birthday", null, "Party time!", "", "#3C5A80"],
  ["birthday", "ad-bd1-cake", "birthday", null, "Another year more fabulous", "HAPPY BIRTHDAY", "#DDE6FA"],
  ["birthday", "b7-ice-cream", "birthday", null, "Have a cool birthday!", "Treat yourself today", "#E6DEFA"],
  ["birthday", "b8-popper", "birthday", null, "Pop pop!", "It’s your birthday!", "#FFF3DC"],
  ["birthday", "ar-bd5-painted-pattern", "birthday", null, "Party Time!", "", "#FFE3EC"],
  ["birthday", "ad-bd6-balloons", "birthday", null, "Up, up & away!", "HAPPY BIRTHDAY", "#DDE6FA"],
  ["birthday", "b9-party-cat", "birthday", null, "Happy purr-thday!", "Have a paw-some day", "#FBCFDF"],
  ["birthday", "mc-bd5-cupcake", "birthday", null, "Sweet as ever", "HAPPY BIRTHDAY", "#CDEDE8"],
  ["birthday", "bd1-cake-slice", "birthday", null, "A slice of birthday fun", "Happy birthday!", "#E6DEFA"],
  ["birthday", "ad-bd8-fireworks", "birthday", null, "Light up the night", "HAPPY BIRTHDAY", "#1F2A44"],
  ["birthday", "bd4-blower", "birthday", null, "Toot toot!", "It’s your birthday!", "#D6F5EA"],
  ["birthday", "bd5-party-dog", "birthday", null, "Happy bark-day!", "Have a paw-some day", "#FBCFDF"],
  ["birthday", "ar-bd4-painted-scene-sunset", "birthday", null, "Happy Birthday! light up the sky", "", "#C2457A"],
  ["birthday", "bd6-party-bunny", "birthday", null, "Some-bunny’s birthday!", "Hop hop hooray", "#E6DEFA"],
  ["birthday", "mc-bd8-heart-balloons", "birthday", null, "Love you loads", "HAPPY BIRTHDAY", "#F4F1EA"],
  ["birthday", "ad-bd10-cheers", "birthday", null, "Cheers to you!", "HAPPY BIRTHDAY", "#3C5A80"],
  ["birthday", "bd7-lollipop", "birthday", null, "You’re so sweet!", "Happy birthday", "#FFF3DC"],
  ["birthday", "bd8-bunting", "birthday", null, "Party time!", "Happy birthday!", "#D6F5EA"],
  ["birthday", "ar-bd2-linocut", "birthday", null, "MAKE A WISH", "", "#F3ECDB"],
  ["birthday", "mc-bd1-cake", "birthday", null, "Another year more fabulous", "HAPPY BIRTHDAY", "#DDE6FA"],
  ["birthday", "bd9-macarons", "birthday", null, "Stack up the fun!", "Happy birthday", "#FBCFDF"],
  ["birthday", "ar-bd9-painted-pattern", "birthday", null, "Hip Hip Hooray!", "", "#3B2A7A"],
  ["birthday", "bd10-sunny", "birthday", null, "Hello, sunshine!", "Have a bright birthday", "#E6DEFA"],
  ["birthday", "mc-bd6-star", "birthday", null, "You’re a star", "HAPPY BIRTHDAY", "#1F2A44"],
  ["birthday", "ad-bd4-camping", "birthday", null, "Wild & free at any age", "HAPPY BIRTHDAY", "#1F2A44"],
  ["birthday", "ar-bd7-watercolour-meadow", "birthday", null, "Bloom & Grow", "HAPPY BIRTHDAY", "#FBF8F2"],
  ["birthday", "mc-bd7-fireworks", "birthday", null, "Light up the night", "HAPPY BIRTHDAY", "#1F2A44"],
  ["birthday", "ad-bd3-road-trip", "birthday", null, "Here’s to new adventures", "HAPPY BIRTHDAY", "#CDEDE8"],
  ["birthday", "ar-bd8-painted-scene-night", "birthday", null, "Cheers to You another adventure", "", "#2B2A6B"],
  ["birthday", "mc-bd4-gift", "birthday", null, "Open a little joy today", "HAPPY BIRTHDAY", "#E7E2F6"],
  ["birthday", "ad-bd9-party", "birthday", null, "Party time!", "", "#3C5A80"],
  ["birthday", "ar-bd1-painted-pattern", "birthday", null, "Happy Birthday", "", "#2A1712"],
  ["birthday", "mc-bd3-candle", "birthday", null, "Make a wish it’s your day", "", "#1F2A44"],
  ["birthday", "ad-bd5-camera", "birthday", null, "Picture-perfect birthday", "HAPPY BIRTHDAY", "#E7E2F6"],
  ["birthday", "ar-bd6-linocut", "birthday", null, "ANOTHER GREAT YEAR", "", "#F6EFE2"],
  ["farewell", "3t-farewell-legend", "leaving", null, "Farewell, legend!", "Thanks for everything. You’ll be so missed!", "#FFF3DC"],
  ["farewell", "3l-teary-cat", "leaving", null, "We’ll miss you!", "Don’t be a stranger", "#FFF3DC"],
  ["farewell", "fw3-airplane", "leaving", null, "Up, up and away!", "Bon voyage from the team", "#5A499C"],
  ["farewell", "3n-new-door", "leaving", null, "Hello, next chapter!", "So proud of you. Go get it!", "#5A499C"],
  ["farewell", "mc-fw4-mountain", "leaving", null, "Onwards & upwards", "GOOD LUCK", "#DDE6FA"],
  ["farewell", "3s-rainbow", "leaving", null, "Sad you’re going, happy for you!", "We’ll miss you loads", "#5A499C"],
  ["farewell", "fw1-moving-box", "leaving", null, "Packing up, moving on!", "We’ll miss you loads", "#FFF3DC"],
  ["farewell", "ar-fw7-watercolour-corners", "leaving", null, "Bon voyage", "FROM ALL OF US", "#FBF8F2"],
  ["farewell", "fw10-map-pin", "leaving", null, "Next stop: awesome!", "Good luck in your new role", "#FBCFDF"],
  ["farewell", "mc-fw7-compass", "leaving", null, "Find your next adventure", "FAREWELL", "#E7E2F6"],
  ["farewell", "3r-signpost", "leaving", null, "Onwards & upwards!", "Good luck in the new role", "#FBCFDF"],
  ["farewell", "ad-fw5-road-trip", "leaving", null, "Next stop: adventure", "FAREWELL", "#E7E2F6"],
  ["farewell", "3m-suitcase", "leaving", null, "Adventure awaits!", "Good luck on your next journey", "#E6DEFA"],
  ["farewell", "3o-blast-off", "leaving", null, "Blast off!", "To your next big thing", "#D6F5EA"],
  ["farewell", "ar-fw5-painted-pattern", "leaving", null, "Farewell, friend", "", "#1E5E5E"],
  ["farewell", "mc-fw6-door", "leaving", null, "New chapter", "GOOD LUCK", "#1F2A44"],
  ["farewell", "3k-paper-plane", "leaving", null, "Off you go!", "We’ll miss you loads", "#5A499C"],
  ["farewell", "ad-fw10-cheers", "leaving", null, "Cheers to what’s next", "FAREWELL", "#3C5A80"],
  ["farewell", "ar-fw10-watercolour-garland", "leaving", null, "Good luck", "YOU’LL BE AMAZING", "#FBF8F2"],
  ["farewell", "3p-keep-growing", "leaving", null, "Keep growing!", "Can’t wait to see you bloom", "#E6DEFA"],
  ["farewell", "3q-coffee-buddy", "leaving", null, "Coffee won’t taste the same", "without you. Good luck!", "#FFF3DC"],
  ["farewell", "mc-fw8-bird", "leaving", null, "Fly high, friend", "WE’LL MISS YOU", "#CDEDE8"],
  ["farewell", "ad-fw8-mountain", "leaving", null, "Climb every mountain", "FAREWELL", "#CDEDE8"],
  ["farewell", "fw2-road-trip", "leaving", null, "New road, new ride!", "Good luck out there", "#D6F5EA"],
  ["farewell", "fw4-sunrise", "leaving", null, "A new day begins!", "Good luck on the next one", "#E6DEFA"],
  ["farewell", "ad-fw4-plane", "leaving", null, "Up, up & away!", "FAREWELL", "#DDE6FA"],
  ["farewell", "ar-fw4-painted-scene-dawn", "leaving", null, "Onwards & upwards new adventures await", "", "#F2A7B8"],
  ["farewell", "fw5-balloon-trip", "leaving", null, "Soar high!", "We’ll miss you", "#D6F5EA"],
  ["farewell", "fw6-compass", "leaving", null, "Follow your compass", "Good luck on your next adventure", "#FFF3DC"],
  ["farewell", "mc-fw10-sunrise", "leaving", null, "Bright days ahead", "GOOD LUCK", "#F4F1EA"],
  ["farewell", "fw7-globe", "leaving", null, "The world is yours!", "Go get it", "#5A499C"],
  ["farewell", "ad-fw2-new-job", "leaving", null, "New job loading...", "GOOD LUCK", "#CDEDE8"],
  ["farewell", "fw8-sailboat", "leaving", null, "Smooth sailing!", "Wishing you the best", "#D6F5EA"],
  ["farewell", "fw9-bindle-bird", "leaving", null, "Fly high, friend!", "The nest won’t be the same", "#E6DEFA"],
  ["farewell", "ar-fw9-painted-pattern", "leaving", null, "So long!", "", "#F2B33D"],
  ["farewell", "ad-fw7-city", "leaving", null, "Big city, big dreams", "GOOD LUCK", "#1F2A44"],
  ["farewell", "ar-fw3-watercolour-meadow", "leaving", null, "We’ll miss you", "GOOD LUCK", "#FBF8F2"],
  ["farewell", "mc-fw2-suitcase", "leaving", null, "Adventure awaits", "FAREWELL", "#F4F1EA"],
  ["farewell", "ad-fw1-rocket", "leaving", null, "Off to great things", "GOOD LUCK", "#1F2A44"],
  ["farewell", "mc-fw1-plane", "leaving", null, "Off you go!", "GOOD LUCK", "#1F2A44"],
  ["farewell", "ar-fw8-painted-scene-sea", "leaving", null, "Next stop: adventure good luck", "", "#CFE6F2"],
  ["farewell", "mc-fw9-cheers", "leaving", null, "Cheers to what’s next", "FAREWELL", "#3C5A80"],
  ["farewell", "ad-fw6-stairs", "leaving", null, "Onwards & upwards", "GOOD LUCK", "#F4F1EA"],
  ["farewell", "ar-fw2-linocut", "leaving", null, "GO SMASH IT", "", "#F3ECDB"],
  ["farewell", "mc-fw5-balloon", "leaving", null, "Soar high", "FAREWELL", "#E6ECEF"],
  ["farewell", "ad-fw9-map", "leaving", null, "New roads ahead", "WE’LL MISS YOU", "#DDE6FA"],
  ["farewell", "ar-fw1-painted-pattern", "leaving", null, "Good Luck!", "", "#BFE3F2"],
  ["farewell", "mc-fw3-sailboat", "leaving", null, "Smooth sailing", "GOOD LUCK", "#CDEDE8"],
  ["farewell", "ad-fw3-briefcase", "leaving", null, "Go smash it!", "GOOD LUCK", "#F4F1EA"],
  ["farewell", "ar-fw6-linocut", "leaving", null, "OFF TO GREAT THINGS", "", "#F6EFE2"],
  ["retirement", "rt1-beach", "retirement", null, "Happy retirement!", "Sun, sand, no emails", "#E6DEFA"],
  ["retirement", "rt6-alarm", "retirement", null, "No more alarms!", "Happy retirement", "#E6DEFA"],
  ["retirement", "rt4-rocking-chair", "retirement", null, "Rock on, retiree!", "You’ve earned it", "#FFF3DC"],
  ["retirement", "rt8-camper", "retirement", null, "Adventure o’clock!", "Happy retirement!", "#5A499C"],
  ["retirement", "mc-rt2-golf", "retirement", null, "Tee time every day", "HAPPY RETIREMENT", "#E6ECEF"],
  ["retirement", "rt2-hammock", "retirement", null, "Time to relax!", "Happy retirement", "#FFF3DC"],
  ["retirement", "rt3-golf", "retirement", null, "Tee time, every day!", "Happy retirement!", "#E6DEFA"],
  ["retirement", "ad-rt5-bike", "retirement", null, "Ride into retirement", "HAPPY RETIREMENT", "#F4F1EA"],
  ["retirement", "rt5-coconut", "retirement", null, "Cheers to forever off!", "Happy retirement", "#D6F5EA"],
  ["retirement", "rt7-watering-can", "retirement", null, "Grow your next chapter", "Happy retirement!", "#FFF3DC"],
  ["retirement", "ar-rt5-painted-pattern", "retirement", null, "No more Mondays!", "", "#FFD6C2"],
  ["retirement", "mc-rt3-balloon", "retirement", null, "Adventure begins", "HAPPY RETIREMENT", "#E7E2F6"],
  ["retirement", "rt9-book-tea", "retirement", null, "Chapter free time", "Happy retirement", "#FBCFDF"],
  ["retirement", "ad-rt8-surf", "retirement", null, "Catch every wave", "HAPPY RETIREMENT", "#F4F1EA"],
  ["retirement", "rt10-slippers", "retirement", null, "Slippers on!", "Enjoy every lazy morning", "#E6DEFA"],
  ["retirement", "ar-rt10-watercolour-border", "retirement", null, "Cheers to freedom", "HAPPY RETIREMENT", "#FBF8F2"],
  ["retirement", "mc-rt7-palm", "retirement", null, "Island time", "HAPPY RETIREMENT", "#DDE6FA"],
  ["retirement", "ad-rt7-camera", "retirement", null, "Go explore!", "HAPPY RETIREMENT", "#DDE6FA"],
  ["retirement", "ar-rt8-painted-scene-dawn", "retirement", null, "Bon voyage! happy retirement", "", "#F2A7B8"],
  ["retirement", "mc-rt1-beach", "retirement", null, "Sun, sand & no emails", "HAPPY RETIREMENT", "#DDE6FA"],
  ["retirement", "ad-rt3-plane", "retirement", null, "Bon voyage!", "HAPPY RETIREMENT", "#E7E2F6"],
  ["retirement", "ar-rt9-painted-pattern", "retirement", null, "Life’s a beach", "", "#1F2A44"],
  ["retirement", "mc-rt10-sunrise", "retirement", null, "Golden years", "HAPPY RETIREMENT", "#F4F1EA"],
  ["retirement", "ad-rt6-golf", "retirement", null, "Tee time every day", "HAPPY RETIREMENT", "#CDEDE8"],
  ["retirement", "ar-rt6-linocut", "retirement", null, "GONE SAILING", "", "#F6EFE2"],
  ["retirement", "mc-rt5-clock", "retirement", null, "Time is all yours", "HAPPY RETIREMENT", "#F4F1EA"],
  ["retirement", "ad-rt2-road-trip", "retirement", null, "Hit the road!", "HAPPY RETIREMENT", "#CDEDE8"],
  ["retirement", "ar-rt3-watercolour-meadow", "retirement", null, "Enjoy every moment", "HAPPY RETIREMENT", "#FBF8F2"],
  ["retirement", "mc-rt9-cheers", "retirement", null, "Cheers to freedom", "HAPPY RETIREMENT", "#3C5A80"],
  ["retirement", "ad-rt4-camping", "retirement", null, "Gone camping", "HAPPY RETIREMENT", "#1F2A44"],
  ["retirement", "mc-rt4-sailboat", "retirement", null, "Set sail", "HAPPY RETIREMENT", "#1F2A44"],
  ["retirement", "ar-rt1-painted-pattern", "retirement", null, "Happy Retirement", "", "#7FD1C7"],
  ["retirement", "mc-rt8-mug", "retirement", null, "Slow mornings", "HAPPY RETIREMENT", "#E6ECEF"],
  ["retirement", "ar-rt2-linocut", "retirement", null, "HAPPY RETIREMENT", "", "#F3ECDB"],
  ["retirement", "ar-rt7-watercolour-corners", "retirement", null, "Time to bloom", "HAPPY RETIREMENT", "#FBF8F2"],
  ["retirement", "mc-rt6-plant", "retirement", null, "Grow your garden", "HAPPY RETIREMENT", "#CDEDE8"],
  ["retirement", "ad-rt1-beach", "retirement", null, "Sun, sand & no emails", "HAPPY RETIREMENT", "#DDE6FA"],
  ["retirement", "ad-rt10-cheers", "retirement", null, "Cheers to freedom!", "HAPPY RETIREMENT", "#3C5A80"],
  ["retirement", "ar-rt4-painted-scene-sea", "retirement", null, "Happy Retirement adventure awaits", "", "#CFE6F2"],
  ["retirement", "ad-rt9-sailboat", "retirement", null, "Set sail!", "HAPPY RETIREMENT", "#1F2A44"],
  ["anniversary", "a1-rings", "anniversary", null, "Happy anniversary!", "Here’s to many more", "#FFF3DC"],
  ["anniversary", "a3-mugs", "anniversary", null, "Another year of us", "Happy anniversary", "#5A499C"],
  ["anniversary", "a10-cheers", "anniversary", null, "Cheers to us!", "Happy anniversary!", "#FBCFDF"],
  ["anniversary", "a2-lovebirds", "anniversary", null, "Still lovebirds", "Happy anniversary!", "#FBCFDF"],
  ["anniversary", "mc-an9-bouquet", "anniversary", null, "Blooming together", "HAPPY ANNIVERSARY", "#1F2A44"],
  ["anniversary", "a4-penguins", "anniversary", null, "Still my penguin", "Happy anniversary!", "#E6DEFA"],
  ["anniversary", "a5-lock", "anniversary", null, "You hold the key", "Happy anniversary, love", "#D6F5EA"],
  ["anniversary", "ad-an9-map", "anniversary", null, "Every road leads to you", "HAPPY ANNIVERSARY", "#DDE6FA"],
  ["anniversary", "ar-an3-watercolour-wreath", "anniversary", null, "Love grows here", "HAPPY ANNIVERSARY", "#FBF8F2"],
  ["anniversary", "a7-calendar", "anniversary", null, "365 more days of us", "Happy anniversary!", "#E6DEFA"],
  ["anniversary", "mc-an1-rings", "anniversary", null, "Still in love", "HAPPY ANNIVERSARY", "#F4F1EA"],
  ["anniversary", "a8-two-plants", "anniversary", null, "Growing together", "Happy anniversary!", "#FFF3DC"],
  ["anniversary", "ad-an7-mugs", "anniversary", null, "Better together", "HAPPY ANNIVERSARY", "#E7E2F6"],
  ["anniversary", "ar-an6-linocut", "anniversary", null, "YEARS OF US", "", "#F3ECDB"],
  ["anniversary", "an1-heart-chain", "anniversary", null, "Still linked", "Happy anniversary", "#FFF3DC"],
  ["anniversary", "a9-heart-balloons", "anniversary", null, "Love you more!", "Happy anniversary", "#D6F5EA"],
  ["anniversary", "ad-an8-lovebirds", "anniversary", null, "Lovebirds still", "HAPPY ANNIVERSARY", "#CDEDE8"],
  ["anniversary", "a6-heart-balloon", "anniversary", null, "Up, up & away!", "Happy anniversary!", "#FFF3DC"],
  ["anniversary", "ar-an8-painted-scene-sunset", "anniversary", null, "Still my favourite adventure", "", "#C2457A"],
  ["anniversary", "an2-socks", "anniversary", null, "Perfect pair", "Happy anniversary!", "#E6DEFA"],
  ["anniversary", "ad-an10-cheers", "anniversary", null, "Here’s to us!", "HAPPY ANNIVERSARY", "#3C5A80"],
  ["anniversary", "ar-an5-painted-pattern", "anniversary", null, "Forever & Always", "", "#FFF4E6"],
  ["anniversary", "an3-shakers", "anniversary", null, "Better together", "Happy anniversary", "#D6F5EA"],
  ["anniversary", "an4-avocado", "anniversary", null, "My other half", "Happy anniversary!", "#FBCFDF"],
  ["anniversary", "mc-an3-heart-balloons", "anniversary", null, "Still the best adventure", "HAPPY ANNIVERSARY", "#CDEDE8"],
  ["anniversary", "an5-puzzle", "anniversary", null, "We just fit!", "Happy anniversary", "#E6DEFA"],
  ["anniversary", "ad-an5-camping", "anniversary", null, "Our favourite adventure", "HAPPY ANNIVERSARY", "#1F2A44"],
  ["anniversary", "an6-coffee-donut", "anniversary", null, "You go with me", "Happy anniversary", "#5A499C"],
  ["anniversary", "ad-an1-rings", "anniversary", null, "Still in love", "HAPPY ANNIVERSARY", "#F4F1EA"],
  ["anniversary", "an7-hourglass", "anniversary", null, "Time flies with you", "Happy anniversary!", "#FFF3DC"],
  ["anniversary", "an8-jars", "anniversary", null, "Perfect match", "Happy anniversary", "#D6F5EA"],
  ["anniversary", "mc-an6-mugs", "anniversary", null, "Better together", "HAPPY ANNIVERSARY", "#E6ECEF"],
  ["anniversary", "an9-bees", "anniversary", null, "Bee mine, always", "Happy anniversary", "#E6DEFA"],
  ["anniversary", "an10-flowers", "anniversary", null, "Growing in love", "Happy anniversary!", "#FBCFDF"],
  ["anniversary", "ar-an7-watercolour-border", "anniversary", null, "Here’s to us", "HAPPY ANNIVERSARY", "#FBF8F2"],
  ["anniversary", "mc-an10-lovebirds", "anniversary", null, "Lovebirds still", "HAPPY ANNIVERSARY", "#CDEDE8"],
  ["anniversary", "mc-an7-home", "anniversary", null, "Home is with you", "HAPPY ANNIVERSARY", "#DDE6FA"],
  ["anniversary", "mc-an4-cheers", "anniversary", null, "Here’s to us", "HAPPY ANNIVERSARY", "#3C5A80"],
  ["anniversary", "ar-an9-painted-pattern", "anniversary", null, "Love you more", "", "#1F2A44"],
  ["anniversary", "ad-an3-road-trip", "anniversary", null, "Still on the road", "HAPPY ANNIVERSARY", "#F4F1EA"],
  ["anniversary", "mc-an8-clock", "anniversary", null, "Time flies with you", "HAPPY ANNIVERSARY", "#F4F1EA"],
  ["anniversary", "ad-an2-plane", "anniversary", null, "Adventures together", "HAPPY ANNIVERSARY", "#DDE6FA"],
  ["anniversary", "ar-an2-linocut", "anniversary", null, "STILL IN LOVE", "", "#F6EFE2"],
  ["anniversary", "mc-an2-constellation", "anniversary", null, "Written in the stars", "HAPPY ANNIVERSARY", "#1F2A44"],
  ["anniversary", "ad-an4-tandem", "anniversary", null, "Still riding together", "HAPPY ANNIVERSARY", "#CDEDE8"],
  ["anniversary", "ar-an10-watercolour-garland", "anniversary", null, "Happy Anniversary", "WITH LOVE", "#FBF8F2"],
  ["anniversary", "mc-an5-letter", "anniversary", null, "Love letters forever", "HAPPY ANNIVERSARY", "#E7E2F6"],
  ["anniversary", "ar-an1-painted-pattern", "anniversary", null, "Happy Anniversary", "", "#FCE4EC"],
  ["anniversary", "ar-an4-painted-scene-night", "anniversary", null, "Happy Anniversary under the same stars", "", "#2B2A6B"],
  ["anniversary", "ad-an6-constellation", "anniversary", null, "Written in the stars", "HAPPY ANNIVERSARY", "#1F2A44"],
  ["wedding", "wd1-bells", "wedding", null, "Wedding bells!", "Congratulations, you two", "#E6DEFA"],
  ["wedding", "3e-just-married-car", "wedding", null, "Just married!", "Beep beep! Congrats!", "#FFF3DC"],
  ["wedding", "2d-the-ring", "wedding", null, "Happily ever after", "Congrats, you two!", "#FFF3DC"],
  ["wedding", "wd4-bottle", "wedding", null, "Pop the bubbly!", "Here’s to the happy couple", "#5A499C"],
  ["wedding", "mc-wd4-heart-balloons", "wedding", null, "Love is in the air", "JUST MARRIED", "#DDE6FA"],
  ["wedding", "3b-wedding-cake", "wedding", null, "Sweetest day ever!", "Congratulations, you two!", "#FFF3DC"],
  ["wedding", "ad-wd3-road-trip", "wedding", null, "Off on the big adventure", "JUST MARRIED", "#DDE6FA"],
  ["wedding", "wd7-arch", "wedding", null, "Two hearts, one love", "Congratulations!", "#E6DEFA"],
  ["wedding", "2c-cheers", "wedding", null, "Cheers to love!", "Just married", "#E6DEFA"],
  ["wedding", "ar-wd6-linocut", "wedding", null, "JUST MARRIED", "", "#F3ECDB"],
  ["wedding", "3a-lovebirds", "wedding", null, "Lovebirds!", "Wishing you a lifetime of cosy together", "#E6DEFA"],
  ["wedding", "mc-wd3-bunting-rings", "wedding", null, "Happily ever after!", "", "#1F2A44"],
  ["wedding", "ad-wd5-cheers", "wedding", null, "Cheers to love!", "ON YOUR WEDDING DAY", "#3C5A80"],
  ["wedding", "wd6-bears", "wedding", null, "Beary in love", "Happy wedding day!", "#FFF3DC"],
  ["wedding", "3c-penguins", "wedding", null, "You found your penguin", "Happy wedding day!", "#D6F5EA"],
  ["wedding", "ar-wd3-watercolour-wreath", "wedding", null, "Happily Ever After", "", "#FBF8F2"],
  ["wedding", "3d-love-letter", "wedding", null, "Sealed with love", "", "#5A499C"],
  ["wedding", "ad-wd1-wreath", "wedding", null, "Just married!", "CONGRATULATIONS", "#F4F1EA"],
  ["wedding", "ar-wd4-painted-scene-sunset", "wedding", null, "Congratulations here’s to your forever", "", "#C2457A"],
  ["wedding", "3f-purrfect-match", "wedding", null, "Purrfect match!", "Congrats on the big day", "#FBCFDF"],
  ["wedding", "3g-love-is-in-the-air", "wedding", null, "Love is in the air!", "", "#E6DEFA"],
  ["wedding", "mc-wd9-lanterns", "wedding", null, "Love lights the way", "ON YOUR WEDDING DAY", "#1F2A44"],
  ["wedding", "3h-better-together", "wedding", null, "Better together", "Here’s to every morning, side by side", "#5A499C"],
  ["wedding", "ad-wd9-cake", "wedding", null, "Sweetest day ever", "CONGRATULATIONS", "#CDEDE8"],
  ["wedding", "3i-bouquet", "wedding", null, "Here’s to forever", "With love on your wedding day", "#FFF3DC"],
  ["wedding", "mc-wd8-bubbly", "wedding", null, "Pop the bubbly", "JUST MARRIED", "#1F2A44"],
  ["wedding", "3j-two-peas", "wedding", null, "Two peas in a pod!", "Made for each other. Congratulations!", "#E6DEFA"],
  ["wedding", "ar-wd2-linocut", "wedding", null, "TWO HEARTS ONE LOVE", "", "#F6EFE2"],
  ["wedding", "ad-wd8-bouquet", "wedding", null, "With love & best wishes", "ON YOUR WEDDING DAY", "#F4F1EA"],
  ["wedding", "wd2-swans", "wedding", null, "Love birds", "Happy wedding day", "#D6F5EA"],
  ["wedding", "mc-wd2-cheers", "wedding", null, "Cheers to love", "ON YOUR WEDDING DAY", "#3C5A80"],
  ["wedding", "wd3-outfits", "wedding", null, "Ready, set, I do!", "Congratulations!", "#FFF3DC"],
  ["wedding", "ar-wd5-painted-pattern", "wedding", null, "Love wins!", "", "#FFF8EC"],
  ["wedding", "mc-wd1-wreath", "wedding", null, "Just married", "CONGRATULATIONS", "#F4F1EA"],
  ["wedding", "wd5-bunnies", "wedding", null, "Hoppily ever after", "Congratulations!", "#FBCFDF"],
  ["wedding", "wd8-heart-cluster", "wedding", null, "All the love!", "Happy wedding day", "#5A499C"],
  ["wedding", "wd9-two-candles", "wedding", null, "Two flames, one heart", "Congratulations", "#FBCFDF"],
  ["wedding", "ad-wd2-honeymoon", "wedding", null, "Honeymoon bound!", "JUST MARRIED", "#CDEDE8"],
  ["wedding", "ar-wd10-watercolour-border", "wedding", null, "Congratulations", "TO THE HAPPY COUPLE", "#FBF8F2"],
  ["wedding", "wd10-otters", "wedding", null, "Otterly in love", "Happy wedding day!", "#D6F5EA"],
  ["wedding", "mc-wd10-letter", "wedding", null, "Signed, sealed married", "CONGRATULATIONS", "#DDE6FA"],
  ["wedding", "ad-wd7-heart-balloons", "wedding", null, "Love is in the air", "JUST MARRIED", "#DDE6FA"],
  ["wedding", "ar-wd7-watercolour-corners", "wedding", null, "With love", "ON YOUR WEDDING DAY", "#FBF8F2"],
  ["wedding", "mc-wd6-dove", "wedding", null, "Two hearts one love", "CONGRATULATIONS", "#3C5A80"],
  ["wedding", "ad-wd6-city", "wedding", null, "Love in the city", "CONGRATULATIONS", "#E7E2F6"],
  ["wedding", "ar-wd8-painted-scene-meadow", "wedding", null, "Cheers to love & a lifetime of joy", "", "#E3F2F7"],
  ["wedding", "mc-wd5-bouquet", "wedding", null, "With love & best wishes", "ON YOUR WEDDING DAY", "#E7E2F6"],
  ["wedding", "ad-wd10-bubbly", "wedding", null, "Pop the bubbly!", "JUST MARRIED", "#1F2A44"],
  ["wedding", "ar-wd1-painted-pattern", "wedding", null, "Just Married", "", "#9BB59B"],
  ["wedding", "mc-wd7-cake", "wedding", null, "Sweetest day", "CONGRATULATIONS", "#CDEDE8"],
  ["wedding", "ad-wd4-bunting-rings", "wedding", null, "Happily ever after!", "", "#1F2A44"],
  ["wedding", "ar-wd9-painted-pattern", "wedding", null, "Oh happy day!", "", "#F8D7DD"],
  ["christmas", "xm1-tree", "christmas", null, "Merry Christmas!", "Wishing you a cosy season", "#FFF3DC"],
  ["christmas", "xm25-tree-night", "christmas", null, "Tree-mendous Christmas!", "Happy holidays", "#5A499C"],
  ["christmas", "xm12-wreath", "christmas", null, "Merry & bright!", "Season’s greetings", "#FFF3DC"],
  ["christmas", "xm3-snowman", "christmas", null, "Let it snow!", "Merry Christmas & happy new year", "#E6DEFA"],
  ["christmas", "xm6-reindeer", "christmas", null, "Oh deer, it’s Christmas!", "Have a merry one", "#5A499C"],
  ["christmas", "xm2-ornament", "christmas", null, "Have a ball this Christmas!", "Merry Christmas", "#5A499C"],
  ["christmas", "mc-xm6-candy-cane", "christmas", null, "Sweet season", "MERRY CHRISTMAS", "#CDEDE8"],
  ["christmas", "ad-xm10-gift", "christmas", null, "Wrapped with love", "MERRY CHRISTMAS", "#1F2A44"],
  ["christmas", "xm11-cocoa", "christmas", null, "Cosy Christmas!", "Warm wishes to you", "#E6DEFA"],
  ["christmas", "ar-xm10-watercolour-border", "christmas", null, "Happy Holidays", "", "#FBF8F2"],
  ["christmas", "mc-xm3-snowflake", "christmas", null, "Let it snow", "HAPPY HOLIDAYS", "#3C5A80"],
  ["christmas", "xm21-presents", "christmas", null, "Wrapped with love", "Merry Christmas", "#D6F5EA"],
  ["christmas", "xm20-gingerbread-house", "christmas", null, "Home for the holidays", "Merry Christmas", "#E6DEFA"],
  ["christmas", "ad-xm1-tree", "christmas", null, "Merry Christmas!", "SEASON’S GREETINGS", "#1F2A44"],
  ["christmas", "ar-xm9-painted-pattern", "christmas", null, "Ho ho ho!", "", "#FFF8EC"],
  ["christmas", "xm15-holly", "christmas", null, "Holly jolly!", "Merry Christmas", "#FFF3DC"],
  ["christmas", "xm4-gingerbread", "christmas", null, "Oh snap!", "Merry Christmas", "#FFF3DC"],
  ["christmas", "mc-xm7-cocoa", "christmas", null, "Cosy Christmas", "WARM WISHES", "#E6ECEF"],
  ["christmas", "ad-xm4-city", "christmas", null, "City lights, Christmas nights", "HAPPY HOLIDAYS", "#1F2A44"],
  ["christmas", "xm5-stocking", "christmas", null, "Stocking full of joy", "Merry Christmas!", "#D6F5EA"],
  ["christmas", "xm7-santa-cat", "christmas", null, "Meowy Christmas!", "Have a purr-fect holiday", "#FBCFDF"],
  ["christmas", "ar-xm3-watercolour-wreath", "christmas", null, "Merry & Bright", "", "#FBF8F2"],
  ["christmas", "xm8-reindeer-dog", "christmas", null, "Yappy holidays!", "Merry Christmas", "#E6DEFA"],
  ["christmas", "ar-xm4-painted-scene-snow", "christmas", null, "Merry Christmas peace & joy", "", "#2F4A7A"],
  ["christmas", "xm9-candy-cane", "christmas", null, "Sweet season!", "Merry Christmas", "#FFF3DC"],
  ["christmas", "xm10-snowflake", "christmas", null, "Snow much fun!", "Happy holidays", "#5A499C"],
  ["christmas", "mc-xm9-gift", "christmas", null, "Wrapped with love", "MERRY CHRISTMAS", "#DDE6FA"],
  ["christmas", "mc-xm2-bauble", "christmas", null, "Have a ball this season", "MERRY CHRISTMAS", "#F4F1EA"],
  ["christmas", "ad-xm5-snowflake", "christmas", null, "Let it snow!", "HAPPY HOLIDAYS", "#3C5A80"],
  ["christmas", "xm13-mittens", "christmas", null, "Warm wishes", "Merry Christmas", "#5A499C"],
  ["christmas", "mc-xm1-tree", "christmas", null, "Merry Christmas", "SEASON’S GREETINGS", "#1F2A44"],
  ["christmas", "xm14-sleigh", "christmas", null, "Sleigh all day!", "Merry Christmas!", "#D6F5EA"],
  ["christmas", "ar-xm5-painted-pattern", "christmas", null, "Let it snow!", "", "#1F2A55"],
  ["christmas", "xm16-cookies", "christmas", null, "Milk & cookies!", "Leave some for Santa", "#E6DEFA"],
  ["christmas", "ad-xm9-cocoa", "christmas", null, "Cosy Christmas", "WARM WISHES", "#DDE6FA"],
  ["christmas", "xm17-snow-globe", "christmas", null, "Shake up some joy!", "Merry Christmas", "#FBCFDF"],
  ["christmas", "xm18-lights", "christmas", null, "Merry & bright", "Happy holidays", "#5A499C"],
  ["christmas", "xm19-fox", "christmas", null, "Fox-tastic Christmas!", "Warm wishes", "#FFF3DC"],
  ["christmas", "ad-xm8-candy-cane", "christmas", null, "Sweet season", "MERRY CHRISTMAS", "#CDEDE8"],
  ["christmas", "ar-xm2-linocut", "christmas", null, "MERRY CHRISTMAS", "", "#F3ECDB"],
  ["christmas", "xm22-bells", "christmas", null, "Jingle all the way!", "Merry Christmas", "#FBCFDF"],
  ["christmas", "mc-xm4-wreath", "christmas", null, "Merry & bright", "MERRY CHRISTMAS", "#F4F1EA"],
  ["christmas", "xm23-star", "christmas", null, "Shine bright!", "Merry Christmas", "#5A499C"],
  ["christmas", "ad-xm2-drive-home", "christmas", null, "Driving home for Christmas", "MERRY CHRISTMAS", "#DDE6FA"],
  ["christmas", "mc-xm8-star", "christmas", null, "Shine bright", "MERRY CHRISTMAS", "#1F2A44"],
  ["christmas", "ad-xm7-stocking", "christmas", null, "Stockings full of joy", "MERRY CHRISTMAS", "#E7E2F6"],
  ["christmas", "xm24-bauble-lilac", "christmas", null, "Merry everything!", "And a happy new year", "#FFF3DC"],
  ["christmas", "ar-xm8-painted-scene-snow", "christmas", null, "Silent night happy holidays", "", "#2F4A7A"],
  ["christmas", "mc-xm10-lanterns", "christmas", null, "Peace & joy", "HAPPY HOLIDAYS", "#1F2A44"],
  ["christmas", "ad-xm3-bauble", "christmas", null, "Have a ball this season", "MERRY CHRISTMAS", "#F4F1EA"],
  ["christmas", "ar-xm1-painted-pattern", "christmas", null, "Merry Christmas", "", "#1E4D3A"],
  ["christmas", "ar-xm6-linocut", "christmas", null, "SEASON’S GREETINGS", "", "#F6EFE2"],
  ["christmas", "ad-xm6-wreath", "christmas", null, "Merry & bright", "MERRY CHRISTMAS", "#F4F1EA"],
  ["christmas", "ar-xm7-watercolour-garland", "christmas", null, "Warm wishes", "MERRY CHRISTMAS", "#FBF8F2"],
  ["christmas", "mc-xm5-stocking", "christmas", null, "Stockings full of joy", "MERRY CHRISTMAS", "#E7E2F6"],
  ["congratulations", "c4-fireworks", "congratulations", null, "Congrats!", "What a moment!", "#5A499C"],
  ["congratulations", "c1-trophy", "congratulations", null, "You did it!", "Congratulations!", "#FFF3DC"],
  ["congratulations", "c8-popper", "congratulations", null, "Big congrats!", "Time to celebrate", "#E6DEFA"],
  ["congratulations", "c10-champagne", "congratulations", null, "Cheers to you!", "Congratulations!", "#E6DEFA"],
  ["congratulations", "mc-cg5-star", "congratulations", null, "You’re a star", "WELL DONE", "#3C5A80"],
  ["congratulations", "c9-star", "congratulations", null, "You’re a star!", "Well done, you!", "#FFF3DC"],
  ["congratulations", "c2-medal", "congratulations", null, "Gold star effort!", "So proud of you", "#E6DEFA"],
  ["congratulations", "ad-cg6-medal", "congratulations", null, "Gold star effort", "CONGRATULATIONS", "#E7E2F6"],
  ["congratulations", "c5-rocket", "congratulations", null, "Sky’s the limit!", "Congratulations on your success", "#D6F5EA"],
  ["congratulations", "cg1-podium", "congratulations", null, "Number one!", "Congratulations, champ", "#FFF3DC"],
  ["congratulations", "ar-cg6-linocut", "congratulations", null, "PROUD OF YOU", "", "#F6EFE2"],
  ["congratulations", "mc-cg4-fireworks", "congratulations", null, "What a moment", "CONGRATULATIONS", "#1F2A44"],
  ["congratulations", "cg3-big-tick", "congratulations", null, "Nailed it!", "Big congrats!", "#E6DEFA"],
  ["congratulations", "ad-cg3-stairs", "congratulations", null, "Top of your game", "CONGRATULATIONS", "#CDEDE8"],
  ["congratulations", "ar-cg5-painted-pattern", "congratulations", null, "Bravo!", "", "#FFF4E6"],
  ["congratulations", "cg2-shooting-star", "congratulations", null, "Star power!", "Congratulations!", "#5A499C"],
  ["congratulations", "c3-rosette", "congratulations", null, "Way to go!", "Congratulations, superstar", "#D6F5EA"],
  ["congratulations", "ad-cg1-trophy", "congratulations", null, "You did it!", "CONGRATULATIONS", "#1F2A44"],
  ["congratulations", "mc-cg3-rosette", "congratulations", null, "Top marks", "CONGRATULATIONS", "#CDEDE8"],
  ["congratulations", "c6-mountain", "congratulations", null, "Top of the world!", "Congrats on the big climb", "#FFF3DC"],
  ["congratulations", "c7-grad-cap", "congratulations", null, "Hats off to you!", "Congratulations, graduate!", "#FBCFDF"],
  ["congratulations", "cg4-new-home", "congratulations", null, "Home sweet home", "Congrats on your new place", "#D6F5EA"],
  ["congratulations", "mc-cg10-balloons", "congratulations", null, "Big congrats!", "CONGRATULATIONS", "#E7E2F6"],
  ["congratulations", "ad-cg4-briefcase", "congratulations", null, "Boss moves", "NEW ROLE", "#F4F1EA"],
  ["congratulations", "cg5-new-baby", "congratulations", null, "Welcome, little one!", "Congratulations on your baby", "#FBCFDF"],
  ["congratulations", "mc-cg2-medal", "congratulations", null, "Gold star effort", "CONGRATULATIONS", "#F4F1EA"],
  ["congratulations", "cg6-crown", "congratulations", null, "You’re the queen!", "Congratulations!", "#E6DEFA"],
  ["congratulations", "ar-cg2-linocut", "congratulations", null, "YOU DID IT!", "", "#F3ECDB"],
  ["congratulations", "ad-cg7-fireworks", "congratulations", null, "What a moment!", "CONGRATULATIONS", "#1F2A44"],
  ["congratulations", "cg7-bubbly", "congratulations", null, "Pop! Congrats!", "Time to celebrate", "#FFF3DC"],
  ["congratulations", "cg8-cloud-nine", "congratulations", null, "On cloud nine!", "Congratulations!", "#E6DEFA"],
  ["congratulations", "mc-cg9-cheers", "congratulations", null, "Here’s to you", "CONGRATULATIONS", "#1F2A44"],
  ["congratulations", "ar-cg9-painted-pattern", "congratulations", null, "Hooray!", "", "#F4743B"],
  ["congratulations", "cg9-bright-idea", "congratulations", null, "Bright spark!", "Congrats on your success", "#5A499C"],
  ["congratulations", "ad-cg9-new-home", "congratulations", null, "Keys to your new home", "NEW HOME", "#CDEDE8"],
  ["congratulations", "cg10-you-rock", "congratulations", null, "You rock!", "Congratulations!", "#D6F5EA"],
  ["congratulations", "ar-cg10-watercolour-meadow", "congratulations", null, "Congrats", "SUPERSTAR", "#FBF8F2"],
  ["congratulations", "ad-cg10-star", "congratulations", null, "You’re a superstar", "WELL DONE", "#3C5A80"],
  ["congratulations", "ar-cg7-watercolour-wreath", "congratulations", null, "Way to go!", "CONGRATULATIONS", "#FBF8F2"],
  ["congratulations", "mc-cg6-bubbly", "congratulations", null, "Pop the champagne", "CONGRATULATIONS", "#DDE6FA"],
  ["congratulations", "ad-cg5-rocket", "congratulations", null, "Sky’s the limit", "CONGRATULATIONS", "#1F2A44"],
  ["congratulations", "ar-cg4-painted-scene-sunset", "congratulations", null, "Congratulations what a moment", "", "#C2457A"],
  ["congratulations", "mc-cg7-mountain", "congratulations", null, "Top of the world", "CONGRATULATIONS", "#E6ECEF"],
  ["congratulations", "ar-cg1-painted-pattern", "congratulations", null, "Congratulations", "", "#4B2A8A"],
  ["congratulations", "mc-cg8-new-home", "congratulations", null, "Home sweet home", "NEW HOME", "#CDEDE8"],
  ["congratulations", "ar-cg3-watercolour-border", "congratulations", null, "Well done you", "CONGRATULATIONS", "#FBF8F2"],
  ["congratulations", "mc-cg1-trophy", "congratulations", null, "You did it!", "CONGRATULATIONS", "#1F2A44"],
  ["congratulations", "ad-cg2-promoted", "congratulations", null, "Promoted! well deserved", "CONGRATULATIONS", "#DDE6FA"],
  ["congratulations", "ad-cg8-bubbly", "congratulations", null, "Pop the champagne", "CONGRATULATIONS", "#DDE6FA"],
  ["congratulations", "ar-cg8-painted-scene-night", "congratulations", null, "You did it! time to celebrate", "", "#2B2A6B"],
  ["get-well", "gw2-thermometer", "get_well", null, "Get well soon!", "Rest up, we miss you", "#E6DEFA"],
  ["get-well", "gw20-flowers", "get_well", null, "Get well soon", "", "#FFF3DC"],
  ["get-well", "gw1-soup", "get_well", null, "Souper get well!", "Feel better soon", "#FFF3DC"],
  ["get-well", "gw12-teddy", "get_well", null, "Beary get well!", "Feel better soon", "#FBCFDF"],
  ["get-well", "mc-gw3-plaster", "get_well", null, "Patching you up", "GET WELL SOON", "#CDEDE8"],
  ["get-well", "gw16-moon", "get_well", null, "Sleep well, heal well", "Get well soon", "#5A499C"],
  ["get-well", "gw11-vase", "get_well", null, "Get well blooms", "Thinking of you", "#FFF3DC"],
  ["get-well", "ad-gw1-soup", "get_well", null, "Souper wishes", "GET WELL SOON", "#DDE6FA"],
  ["get-well", "ar-gw6-linocut", "get_well", null, "REST & RECOVER", "", "#F6EFE2"],
  ["get-well", "mc-gw6-moon", "get_well", null, "Sleep well, heal well", "GET WELL SOON", "#3C5A80"],
  ["get-well", "gw14-sun-cloud", "get_well", null, "Sunnier days ahead", "Feel better soon", "#D6F5EA"],
  ["get-well", "gw7-tea-lemon", "get_well", null, "Sip, rest, repeat", "Feel better soon", "#E6DEFA"],
  ["get-well", "gw3-plaster", "get_well", null, "Patching you up", "Get well soon!", "#D6F5EA"],
  ["get-well", "ar-gw10-watercolour-garland", "get_well", null, "Thinking of you", "GET WELL SOON", "#FBF8F2"],
  ["get-well", "mc-gw7-sun", "get_well", null, "Brighter days ahead", "GET WELL SOON", "#CDEDE8"],
  ["get-well", "gw13-cat-blanket", "get_well", null, "Cosy up & rest", "Get well soon", "#E6DEFA"],
  ["get-well", "ad-gw10-vase", "get_well", null, "Feel better soon!", "GET WELL SOON", "#E7E2F6"],
  ["get-well", "gw4-tissues", "get_well", null, "Achoo!", "Bless you. Feel better soon", "#FBCFDF"],
  ["get-well", "gw5-hot-water-bottle", "get_well", null, "Warm wishes", "Get well soon", "#E6DEFA"],
  ["get-well", "ar-gw5-painted-pattern", "get_well", null, "Sending sunshine", "", "#D6F5EA"],
  ["get-well", "mc-gw4-thermometer", "get_well", null, "Feel better soon", "GET WELL SOON", "#E7E2F6"],
  ["get-well", "gw6-bear-bed", "get_well", null, "Rest up, buddy", "Get well soon", "#FFF3DC"],
  ["get-well", "ad-gw5-plaster", "get_well", null, "Patching you up", "GET WELL SOON", "#CDEDE8"],
  ["get-well", "gw8-orange", "get_well", null, "Vitamin C you soon!", "Get well soon", "#D6F5EA"],
  ["get-well", "ad-gw8-plant", "get_well", null, "Grow stronger", "GET WELL SOON", "#F4F1EA"],
  ["get-well", "gw9-apple", "get_well", null, "An apple a day...", "Get well soon!", "#FFF3DC"],
  ["get-well", "ar-gw8-painted-scene-dawn", "get_well", null, "Healing wishes get well soon", "", "#F2A7B8"],
  ["get-well", "gw10-honey", "get_well", null, "Feel better, honey", "Sending sweet wishes", "#E6DEFA"],
  ["get-well", "gw15-socks", "get_well", null, "Feet up, rest up!", "Get well soon", "#FFF3DC"],
  ["get-well", "mc-gw8-mug", "get_well", null, "Warm wishes", "GET WELL SOON", "#DDE6FA"],
  ["get-well", "gw17-ice-pack", "get_well", null, "Ruff day?", "Hope you feel better soon", "#E6DEFA"],
  ["get-well", "ad-gw2-bike", "get_well", null, "Back on your bike soon", "GET WELL SOON", "#CDEDE8"],
  ["get-well", "gw18-plant", "get_well", null, "Grow stronger", "Get well soon", "#D6F5EA"],
  ["get-well", "gw19-pillow", "get_well", null, "Rest mode: on", "Get well soon!", "#FBCFDF"],
  ["get-well", "ar-gw4-painted-scene-meadow", "get_well", null, "Get well soon brighter days ahead", "", "#E3F2F7"],
  ["get-well", "mc-gw2-tea", "get_well", null, "Rest & recover", "GET WELL SOON", "#F4F1EA"],
  ["get-well", "ar-gw9-painted-pattern", "get_well", null, "Feel better!", "", "#FFF1A8"],
  ["get-well", "mc-gw9-vase", "get_well", null, "Thinking of you", "GET WELL SOON", "#F4F1EA"],
  ["get-well", "ad-gw7-rainbow", "get_well", null, "Sunshine on the way", "GET WELL SOON", "#DDE6FA"],
  ["get-well", "ar-gw3-watercolour-meadow", "get_well", null, "Feel better soon", "", "#FBF8F2"],
  ["get-well", "mc-gw10-plant", "get_well", null, "Grow stronger", "GET WELL SOON", "#E7E2F6"],
  ["get-well", "ad-gw9-mug", "get_well", null, "Warm wishes", "GET WELL SOON", "#CDEDE8"],
  ["get-well", "ar-gw2-linocut", "get_well", null, "GET WELL SOON", "", "#F3ECDB"],
  ["get-well", "mc-gw5-tulips", "get_well", null, "Sending sunny wishes", "GET WELL SOON", "#E6ECEF"],
  ["get-well", "ad-gw6-tea", "get_well", null, "Rest & recover", "GET WELL SOON", "#E7E2F6"],
  ["get-well", "ad-gw4-sun", "get_well", null, "Brighter days ahead", "GET WELL SOON", "#F4F1EA"],
  ["get-well", "ar-gw7-watercolour-wreath", "get_well", null, "Get well soon", "WITH LOVE", "#FBF8F2"],
  ["get-well", "mc-gw1-soup", "get_well", null, "Souper wishes", "GET WELL SOON", "#DDE6FA"],
  ["get-well", "ad-gw3-camping", "get_well", null, "Rest up for the next adventure", "GET WELL SOON", "#1F2A44"],
  ["get-well", "ar-gw1-painted-pattern", "get_well", null, "Get Well Soon", "", "#BFE3F2"],
  ["thank-you", "ty1-big-heart", "thank_you", null, "Thank you!", "From the bottom of our hearts", "#FFF3DC"],
  ["thank-you", "ty9-letter", "thank_you", null, "Thank you!", "", "#5A499C"],
  ["thank-you", "ty2-sunflower", "thank_you", null, "You make us sunny", "Thank you!", "#E6DEFA"],
  ["thank-you", "ty19-cloud-nine", "thank_you", null, "Thanks a million!", "You made our day", "#E6DEFA"],
  ["thank-you", "ty11-trophy", "thank_you", null, "You’re the best!", "Thanks a million", "#FFF3DC"],
  ["thank-you", "mc-ty5-latte", "thank_you", null, "Thanks a latte", "THANK YOU", "#F4F1EA"],
  ["thank-you", "ad-ty1-team-mvp", "thank_you", null, "Team MVP!", "THANK YOU", "#1F2A44"],
  ["thank-you", "ty12-star", "thank_you", null, "Thanks, superstar!", "We couldn’t have done it without you", "#E6DEFA"],
  ["thank-you", "ar-ty10-watercolour-corners", "thank_you", null, "Thank you so much", "", "#FBF8F2"],
  ["thank-you", "ty16-rainbow", "thank_you", null, "You brighten our days", "Thank you", "#5A499C"],
  ["thank-you", "ty20-bouquet", "thank_you", null, "Thank you kindly", "With gratitude", "#FBCFDF"],
  ["thank-you", "mc-ty4-gift", "thank_you", null, "You’re a gift", "THANK YOU", "#CDEDE8"],
  ["thank-you", "ad-ty4-rocket", "thank_you", null, "You’re out of this world", "THANK YOU", "#1F2A44"],
  ["thank-you", "ar-ty8-painted-scene-sunset", "thank_you", null, "Thank you for everything", "", "#C2457A"],
  ["thank-you", "ty17-balloons", "thank_you", null, "Thanks a bunch!", "You’re amazing", "#FFF3DC"],
  ["thank-you", "ty3-bee", "thank_you", null, "Thank bee-you!", "You’re the bee’s knees", "#D6F5EA"],
  ["thank-you", "ty4-owl", "thank_you", null, "Owl-ways grateful", "Thank you so much", "#FFF3DC"],
  ["thank-you", "mc-ty3-star", "thank_you", null, "You’re a star", "THANK YOU", "#3C5A80"],
  ["thank-you", "ty5-cactus", "thank_you", null, "Thanks a lot!", "You’re a real sharp one", "#E6DEFA"],
  ["thank-you", "ar-ty7-watercolour-wreath", "thank_you", null, "Thank you", "WITH GRATITUDE", "#FBF8F2"],
  ["thank-you", "ty6-latte", "thank_you", null, "Thanks a latte!", "We appreciate you", "#FBCFDF"],
  ["thank-you", "mc-ty7-trophy", "thank_you", null, "You’re the best", "THANK YOU", "#1F2A44"],
  ["thank-you", "ad-ty8-latte", "thank_you", null, "Thanks a latte!", "THANK YOU", "#F4F1EA"],
  ["thank-you", "ty7-melon", "thank_you", null, "One in a melon!", "Thank you", "#D6F5EA"],
  ["thank-you", "ar-ty1-painted-pattern", "thank_you", null, "Thank You", "", "#FCD5E0"],
  ["thank-you", "ty8-berry", "thank_you", null, "Thank you berry much", "", "#E6DEFA"],
  ["thank-you", "ty10-gift", "thank_you", null, "You’re a gift!", "Thank you for everything", "#D6F5EA"],
  ["thank-you", "mc-ty10-vase", "thank_you", null, "With gratitude", "THANK YOU", "#1F2A44"],
  ["thank-you", "ad-ty7-gift", "thank_you", null, "You’re a gift", "THANK YOU", "#E7E2F6"],
  ["thank-you", "ty13-hug", "thank_you", null, "Thanks for the hugs", "You’re the best", "#FBCFDF"],
  ["thank-you", "ty14-cupcake", "thank_you", null, "So sweet of you!", "Thank you", "#FFF3DC"],
  ["thank-you", "ad-ty9-sun", "thank_you", null, "You brighten our days", "THANK YOU", "#DDE6FA"],
  ["thank-you", "ty15-donut", "thank_you", null, "Donut know what we’d do", "without you. Thank you!", "#E6DEFA"],
  ["thank-you", "ty18-tulips", "thank_you", null, "You help us grow", "Thank you", "#D6F5EA"],
  ["thank-you", "ar-ty4-painted-scene-meadow", "thank_you", null, "Thank you you light up our days", "", "#E3F2F7"],
  ["thank-you", "mc-ty6-tulips", "thank_you", null, "You help us grow", "THANK YOU", "#E7E2F6"],
  ["thank-you", "ad-ty6-star", "thank_you", null, "You’re a star", "THANK YOU", "#3C5A80"],
  ["thank-you", "ar-ty3-watercolour-meadow", "thank_you", null, "Thanks a bunch!", "", "#FBF8F2"],
  ["thank-you", "mc-ty8-heart-balloons", "thank_you", null, "Thanks a million", "THANK YOU", "#E6ECEF"],
  ["thank-you", "ad-ty5-bouquet", "thank_you", null, "Thanks a bunch!", "THANK YOU", "#DDE6FA"],
  ["thank-you", "ar-ty9-painted-pattern", "thank_you", null, "Thanks!", "", "#3A1F3D"],
  ["thank-you", "mc-ty2-letter", "thank_you", null, "From the heart", "THANK YOU", "#DDE6FA"],
  ["thank-you", "ad-ty3-stairs", "thank_you", null, "You lift us up", "THANK YOU", "#F4F1EA"],
  ["thank-you", "mc-ty9-sun", "thank_you", null, "You brighten our days", "THANK YOU", "#DDE6FA"],
  ["thank-you", "ad-ty10-cheers", "thank_you", null, "Cheers to you!", "THANK YOU", "#3C5A80"],
  ["thank-you", "ar-ty6-linocut", "thank_you", null, "YOU’RE A STAR", "", "#F6EFE2"],
  ["thank-you", "ad-ty2-laptop", "thank_you", null, "Thanks for all you do", "THANK YOU", "#CDEDE8"],
  ["thank-you", "ar-ty5-painted-pattern", "thank_you", null, "Grateful for you", "", "#FFE08A"],
  ["thank-you", "mc-ty1-bouquet", "thank_you", null, "Thanks a bunch", "THANK YOU", "#F4F1EA"],
  ["thank-you", "ar-ty2-linocut", "thank_you", null, "THANK YOU", "", "#F3ECDB"],
  ["sympathy-colleague", "s1-candle", "sympathy", "colleague", "Thinking of you", "With love from all of us", "#E6DEFA"],
  ["sympathy-colleague", "s7-forget-me-not", "sympathy", "colleague", "Sorry for your loss", "", "#D6F5EA"],
  ["sympathy-colleague", "s2-dove", "sympathy", "colleague", "With deepest sympathy", "We’re here for you", "#D6F5EA"],
  ["sympathy-colleague", "s4-moon", "sympathy", "colleague", "Holding you in our hearts", "From all of us", "#5A499C"],
  ["sympathy-colleague", "mc-sy10-vase", "sympathy", "colleague", "Holding you close", "THINKING OF YOU", "#CDEDE8"],
  ["sympathy-colleague", "s6-lanterns", "sympathy", "colleague", "With love & light", "Our thoughts are with you", "#5A499C"],
  ["sympathy-colleague", "ad-sy8-tea", "sympathy", "colleague", "Sending gentle hugs", "HERE FOR YOU", "#DDE6FA"],
  ["sympathy-colleague", "s5-hug", "sympathy", "colleague", "Sending big hugs", "Thinking of you", "#FBCFDF"],
  ["sympathy-colleague", "ar-sy5-painted-pattern", "sympathy", "colleague", "Thinking of you", "", "#E7E2F6"],
  ["sympathy-colleague", "s3-teacup", "sympathy", "colleague", "Here for you", "Take all the time you need", "#FFF3DC"],
  ["sympathy-colleague", "ad-sy1-candle", "sympathy", "colleague", "Thinking of you", "WITH SYMPATHY", "#1F2A44"],
  ["sympathy-colleague", "s10-branch-bird", "sympathy", "colleague", "You’re not alone", "With love from all of us", "#E6DEFA"],
  ["sympathy-colleague", "s8-tulips", "sympathy", "colleague", "Wishing you gentle days", "With love from the team", "#E6DEFA"],
  ["sympathy-colleague", "ar-sy3-watercolour-wreath", "sympathy", "colleague", "With love & sympathy", "", "#FBF8F2"],
  ["sympathy-colleague", "s9-feather", "sympathy", "colleague", "Softly thinking of you", "We’re all here for you", "#FFF3DC"],
  ["sympathy-colleague", "mc-sy2-dove", "sympathy", "colleague", "Peace & comfort", "WITH SYMPATHY", "#3C5A80"],
  ["sympathy-partner", "l6-candle", "sympathy", "partner", "Remembering with love", "Thinking of you always", "#FBCFDF"],
  ["sympathy-colleague", "ar-sy8-painted-scene-nightsoft", "sympathy", "colleague", "Love & light always", "", "#3C5A80"],
  ["sympathy-colleague", "mc-sy8-constellation", "sympathy", "colleague", "Always shining", "IN LOVING MEMORY", "#1F2A44"],
  ["sympathy-partner", "l1-moon-stars", "sympathy", "partner", "Love never ends", "Thinking of you", "#5A499C"],
  ["sympathy-colleague", "ad-sy5-moon", "sympathy", "colleague", "Forever in our hearts", "IN LOVING MEMORY", "#1F2A44"],
  ["sympathy-colleague", "ar-sy7-watercolour-corners", "sympathy", "colleague", "Holding you close", "WITH LOVE", "#FBF8F2"],
  ["sympathy-partner", "l2-lanterns", "sympathy", "partner", "Their light lives on", "Holding you close", "#E6DEFA"],
  ["sympathy-partner", "l3-two-stars", "sympathy", "partner", "Always with you", "With deepest sympathy", "#5A499C"],
  ["sympathy-partner", "l4-heart-tree", "sympathy", "partner", "Love lives on", "Wrapped in love", "#FFF3DC"],
  ["sympathy-partner", "l7-dove", "sympathy", "partner", "With deepest love", "We are here for you", "#E6DEFA"],
  ["sympathy-colleague", "mc-sy7-tea", "sympathy", "colleague", "Sending gentle hugs", "HERE FOR YOU", "#E7E2F6"],
  ["sympathy-colleague", "mc-sy9-wreath", "sympathy", "colleague", "Deepest condolences", "WITH SYMPATHY", "#F4F1EA"],
  ["sympathy-partner", "l8-forget-me-not", "sympathy", "partner", "Forever remembered", "", "#FFF3DC"],
  ["sympathy-partner", "l10-hug", "sympathy", "partner", "Sending all our love", "Thinking of you", "#E6DEFA"],
  ["sympathy-colleague", "ar-sy10-watercolour-garland", "sympathy", "colleague", "In loving memory", "", "#FBF8F2"],
  ["sympathy-colleague", "mc-sy6-lanterns", "sympathy", "colleague", "Love & light", "THINKING OF YOU", "#3C5A80"],
  ["sympathy-colleague", "ad-sy2-dove", "sympathy", "colleague", "Peace & comfort", "WITH SYMPATHY", "#3C5A80"],
  ["sympathy-colleague", "ar-sy9-painted-pattern", "sympathy", "colleague", "Sending love", "", "#2F4A6E"],
  ["sympathy-partner", "l5-feather", "sympathy", "partner", "Gentle hugs for you", "We’re so sorry", "#E6DEFA"],
  ["sympathy-partner", "l9-rainbow", "sympathy", "partner", "Holding you in our hearts", "With love", "#D6F5EA"],
  ["sympathy-colleague", "ad-sy9-constellation", "sympathy", "colleague", "Always shining", "IN LOVING MEMORY", "#1F2A44"],
  ["sympathy-tears", "st1-rain-cloud", "sympathy", "comfort", "So sorry for your loss", "Sending you gentle hugs", "#E6DEFA"],
  ["sympathy-tears", "st4-teary-cat", "sympathy", "comfort", "Thinking of you", "With love and hugs", "#FBCFDF"],
  ["sympathy-colleague", "mc-sy4-tulips", "sympathy", "colleague", "With love & sympathy", "THINKING OF YOU", "#E6ECEF"],
  ["sympathy-tears", "st2-teary-bear", "sympathy", "comfort", "Beary big hugs", "Thinking of you", "#FFF3DC"],
  ["sympathy-tears", "st8-sun-cloud", "sympathy", "comfort", "Brighter days will come", "Thinking of you", "#E6DEFA"],
  ["sympathy-colleague", "ad-sy10-vase", "sympathy", "colleague", "Holding you close", "THINKING OF YOU", "#CDEDE8"],
  ["sympathy-colleague", "ar-sy6-linocut", "sympathy", "colleague", "WITH DEEPEST SYMPATHY", "", "#F3EFE8"],
  ["sympathy-tears", "st7-mended-heart", "sympathy", "comfort", "Healing hugs", "Take all the time you need", "#FFF3DC"],
  ["sympathy-tears", "st5-teary-bunny", "sympathy", "comfort", "Hugs for you", "Sorry you’re hurting", "#E6DEFA"],
  ["sympathy-colleague", "mc-sy3-moon", "sympathy", "colleague", "Forever in our hearts", "IN LOVING MEMORY", "#1F2A44"],
  ["sympathy-colleague", "ad-sy3-sunrise", "sympathy", "colleague", "Brighter days will come", "THINKING OF YOU", "#F4F1EA"],
  ["sympathy-tears", "st3-teary-puppy", "sympathy", "comfort", "Sending puppy hugs", "We’re here for you", "#D6F5EA"],
  ["sympathy-tears", "st10-teary-duck", "sympathy", "comfort", "Sending love", "We’re thinking of you", "#D6F5EA"],
  ["sympathy-colleague", "ad-sy7-lanterns", "sympathy", "colleague", "Their light lives on", "THINKING OF YOU", "#3C5A80"],
  ["sympathy-colleague", "ar-sy4-painted-scene-dawn", "sympathy", "colleague", "Forever in our hearts with love", "", "#F2A7B8"],
  ["sympathy-tears", "st6-teary-penguin", "sympathy", "comfort", "Here with tissues", "And a big hug", "#D6F5EA"],
  ["sympathy-tears", "st9-teary-koala", "sympathy", "comfort", "Koala-ty hugs", "We’re so sorry", "#FBCFDF"],
  ["sympathy-colleague", "mc-sy1-candle", "sympathy", "colleague", "Thinking of you", "WITH SYMPATHY", "#1F2A44"],
  ["sympathy-colleague", "mc-sy5-feather", "sympathy", "colleague", "Softly remembered", "WITH SYMPATHY", "#F4F1EA"],
  ["sympathy-pet", "p3-paw-heart", "sympathy", "pet", "Paw prints on your heart", "Thinking of you", "#5A499C"],
  ["sympathy-pet", "p4-rainbow-bridge", "sympathy", "pet", "Run free, sweet friend", "Until the rainbow bridge", "#E6DEFA"],
  ["sympathy-colleague", "ad-sy6-tulips", "sympathy", "colleague", "With love & sympathy", "THINKING OF YOU", "#E7E2F6"],
  ["sympathy-colleague", "ad-sy4-rainbow", "sympathy", "colleague", "Love & light", "SENDING LOVE", "#CDEDE8"],
  ["sympathy-pet", "p1-sleeping-cat", "sympathy", "pet", "Forever in your heart", "So sorry about your best friend", "#E6DEFA"],
  ["sympathy-colleague", "ar-sy2-linocut", "sympathy", "colleague", "THINKING OF YOU", "", "#F3EFE8"],
  ["sympathy-pet", "p10-dog-cloud", "sympathy", "pet", "Until we meet again", "With love and sympathy", "#FBCFDF"],
  ["sympathy-colleague", "ar-sy1-painted-pattern", "sympathy", "colleague", "With Sympathy", "", "#C9D6C3"],
  ["sympathy-pet", "p2-angel-dog", "sympathy", "pet", "Such a good friend", "Sending love at this sad time", "#FFF3DC"],
  ["sympathy-pet", "p5-paw-trail", "sympathy", "pet", "Always by your side", "So sorry for your loss", "#5A499C"],
  ["sympathy-pet", "p8-angel-cat", "sympathy", "pet", "Purring in heaven", "So sorry about your kitty", "#E6DEFA"],
  ["sympathy-pet", "p7-collar", "sympathy", "pet", "Forever loved", "Sending you a big hug", "#D6F5EA"],
  ["sympathy-pet", "p6-bowl", "sympathy", "pet", "They were so loved", "Thinking of you both", "#FFF3DC"],
  ["sympathy-pet", "p9-bunny", "sympathy", "pet", "Little paws, big love", "Thinking of you", "#D6F5EA"],
  ["baby-shower", "bs7-booties", "baby_shower", null, "Tiny toes coming soon", "Happy baby shower", "#FFF3DC"],
  ["baby-shower", "bs3-bottle", "baby_shower", null, "Baby on the way!", "So excited for you", "#D6F5EA"],
  ["baby-shower", "bs2-rattle", "baby_shower", null, "Shake, rattle & roll!", "Baby is on the way", "#E6DEFA"],
  ["baby-shower", "bs5-stork", "baby_shower", null, "Special delivery!", "A little bundle is coming", "#CFE8F7"],
  ["baby-shower", "mc-bs6-heart-balloons", "baby_shower", null, "Bundle of joy", "BABY SHOWER", "#E6ECEF"],
  ["baby-shower", "bs16-bear", "baby_shower", null, "Beary excited!", "Congratulations on your bump", "#FBCFDF"],
  ["baby-shower", "ad-bs3-rattle", "baby_shower", null, "Little one on the way", "BABY SHOWER", "#E7E2F6"],
  ["baby-shower", "bs24-twinkle", "baby_shower", null, "Twinkle, twinkle", "Little star is on the way", "#5A499C"],
  ["baby-shower", "ar-bs9-painted-pattern", "baby_shower", null, "Hello world!", "", "#D6F5EA"],
  ["baby-shower", "bs11-elephant", "baby_shower", null, "Welcome, little peanut", "Happy baby shower", "#D6F5EA"],
  ["baby-shower", "mc-bs7-star", "baby_shower", null, "Twinkle little star", "BABY SHOWER", "#3C5A80"],
  ["baby-shower", "bs4-pram", "baby_shower", null, "Baby on board!", "Congratulations!", "#FFF3DC"],
  ["baby-shower", "bs23-cloud-nine", "baby_shower", null, "On cloud nine!", "Congratulations!", "#CFE8F7"],
  ["baby-shower", "ad-bs7-rainbow", "baby_shower", null, "Over the rainbow", "BABY SHOWER", "#F4F1EA"],
  ["baby-shower", "ar-bs7-watercolour-garland", "baby_shower", null, "Sweet baby", "BABY SHOWER", "#FBF8F2"],
  ["baby-shower", "bs31-baby-love", "baby_shower", null, "Baby love", "Happy baby shower", "#FFF3DC"],
  ["baby-shower", "mc-bs4-booties", "baby_shower", null, "Tiny toes, big love", "BABY SHOWER", "#F4F1EA"],
  ["baby-shower", "bs1-oh-baby", "baby_shower", null, "Oh baby!", "Welcome to the world, little one", "#FFF3DC"],
  ["baby-shower", "bs6-duck", "baby_shower", null, "Rub-a-dub, baby!", "Splashing into the world soon", "#E6DEFA"],
  ["baby-shower", "ad-bs4-onesie", "baby_shower", null, "Hello, little one", "WELCOME BABY", "#CDEDE8"],
  ["baby-shower", "ar-bs2-linocut", "baby_shower", null, "HELLO BABY", "", "#F3ECDB"],
  ["baby-shower", "bs8-pacifier", "baby_shower", null, "Oh so sweet!", "Happy baby shower", "#D6F5EA"],
  ["baby-shower", "bs9-mobile", "baby_shower", null, "Sweet dreams", "Little one, we can’t wait", "#E6DEFA"],
  ["baby-shower", "ar-bs3-watercolour-wreath", "baby_shower", null, "Welcome little one", "", "#FBF8F2"],
  ["baby-shower", "bs10-blocks", "baby_shower", null, "A, B, C... baby!", "Happy baby shower", "#FFF3DC"],
  ["baby-shower", "mc-bs2-rattle", "baby_shower", null, "Little one on the way", "BABY SHOWER", "#E7E2F6"],
  ["baby-shower", "mc-bs10-cupcake", "baby_shower", null, "Sweet baby", "BABY SHOWER", "#CDEDE8"],
  ["baby-shower", "bs12-whale", "baby_shower", null, "Whale hello, baby!", "Congratulations!", "#E6DEFA"],
  ["baby-shower", "ad-bs8-bird", "baby_shower", null, "A little bird told us", "BABY SHOWER", "#DDE6FA"],
  ["baby-shower", "bs13-sheep", "baby_shower", null, "Ewe are so loved", "Happy baby shower", "#CFE8F7"],
  ["baby-shower", "ar-bs4-painted-scene-night", "baby_shower", null, "Twinkle twinkle baby is coming", "", "#2B2A6B"],
  ["baby-shower", "bs14-bib", "baby_shower", null, "Little bib, big love", "Congratulations!", "#E6DEFA"],
  ["baby-shower", "ad-bs2-rocket", "baby_shower", null, "Little astronaut landing soon", "BABY SHOWER", "#1F2A44"],
  ["baby-shower", "bs15-clothesline", "baby_shower", null, "Tiny clothes, big love", "Happy baby shower", "#FFF3DC"],
  ["baby-shower", "bs17-bunny", "baby_shower", null, "Some-bunny new!", "Happy baby shower", "#D6F5EA"],
  ["baby-shower", "ad-bs5-booties", "baby_shower", null, "Tiny toes, big love", "BABY SHOWER", "#F4F1EA"],
  ["baby-shower", "bs18-penguin", "baby_shower", null, "Little waddler!", "Coming soon", "#E6DEFA"],
  ["baby-shower", "bs19-giraffe", "baby_shower", null, "Hello, little one!", "Happy baby shower", "#FFF3DC"],
  ["baby-shower", "mc-bs3-onesie", "baby_shower", null, "Hello, little one", "WELCOME BABY", "#CDEDE8"],
  ["baby-shower", "ar-bs6-linocut", "baby_shower", null, "LITTLE ONE ON THE WAY", "", "#F6EFE2"],
  ["baby-shower", "ar-bs5-painted-pattern", "baby_shower", null, "Baby Shower", "", "#FCE4EC"],
  ["baby-shower", "mc-bs1-pram", "baby_shower", null, "Oh baby!", "BABY SHOWER", "#DDE6FA"],
  ["baby-shower", "bs20-twins", "baby_shower", null, "Double the fun!", "Twins! Congratulations", "#E6DEFA"],
  ["baby-shower", "bs21-owl", "baby_shower", null, "Owl-ways loved", "Happy baby shower", "#FBCFDF"],
  ["baby-shower", "ad-bs10-cupcake", "baby_shower", null, "Sweet baby", "BABY SHOWER", "#E7E2F6"],
  ["baby-shower", "mc-bs9-bird", "baby_shower", null, "A little bird told us", "BABY SHOWER", "#DDE6FA"],
  ["baby-shower", "bs22-moon", "baby_shower", null, "Love you to the moon", "Welcome, little one", "#5A499C"],
  ["baby-shower", "bs25-balloon", "baby_shower", null, "Up, up, baby!", "Happy baby shower", "#D6F5EA"],
  ["baby-shower", "bs26-bee", "baby_shower", null, "Oh bee-by!", "Sweet as honey", "#FFF3DC"],
  ["baby-shower", "ad-bs6-moon", "baby_shower", null, "Love you to the moon", "BABY SHOWER", "#1F2A44"],
  ["baby-shower", "bs27-cupcake", "baby_shower", null, "Sweet baby!", "Happy baby shower", "#E6DEFA"],
  ["baby-shower", "ar-bs10-watercolour-corners", "baby_shower", null, "Bundle of joy", "", "#FBF8F2"],
  ["baby-shower", "bs28-balloons", "baby_shower", null, "Hello, baby!", "Let’s celebrate", "#FFF3DC"],
  ["baby-shower", "ar-bs8-painted-scene-meadow", "baby_shower", null, "Over the moon for you", "", "#E3F2F7"],
  ["baby-shower", "mc-bs8-rainbow", "baby_shower", null, "Over the rainbow", "BABY SHOWER", "#F4F1EA"],
  ["baby-shower", "bs29-its-a-boy", "baby_shower", null, "It’s a boy!", "Congratulations!", "#CFE8F7"],
  ["baby-shower", "ad-bs9-heart-balloons", "baby_shower", null, "Bundle of joy", "BABY SHOWER", "#CDEDE8"],
  ["baby-shower", "bs30-its-a-girl", "baby_shower", null, "It’s a girl!", "Congratulations!", "#FBCFDF"],
  ["baby-shower", "ar-bs1-painted-pattern", "baby_shower", null, "Oh Baby!", "", "#CFE8F7"],
  ["baby-shower", "bs32-little-star", "baby_shower", null, "Little star", "Coming soon to shine", "#E6DEFA"],
  ["baby-shower", "ad-bs1-pram", "baby_shower", null, "Oh baby!", "BABY SHOWER", "#DDE6FA"],
  ["baby-shower", "bs33-lollipop", "baby_shower", null, "Sweet as can be", "Happy baby shower", "#D6F5EA"],
  ["baby-shower", "bs34-macarons", "baby_shower", null, "Sweet treats for baby", "Happy baby shower", "#FFF3DC"],
  ["baby-shower", "mc-bs5-moon", "baby_shower", null, "Love you to the moon", "BABY SHOWER", "#1F2A44"],
  ["baby-shower", "bs35-sunshine", "baby_shower", null, "Hello, sunshine!", "A little light is coming", "#E6DEFA"],
  ["baby-shower", "bs36-pram-blue", "baby_shower", null, "Rolling in soon!", "Happy baby shower", "#FFF3DC"],
  ["baby-shower", "bs37-bundle", "baby_shower", null, "Bundle of joy", "Congratulations!", "#FBCFDF"],
  ["baby-shower", "bs38-just-ducky", "baby_shower", null, "Just ducky!", "Happy baby shower", "#D6F5EA"],
  ["baby-shower", "bs39-bear-lilac", "baby_shower", null, "Beary loved", "Welcome, little one", "#FFF3DC"],
  ["baby-shower", "bs40-hop-hooray", "baby_shower", null, "Hop, hop, hooray!", "Happy baby shower", "#E6DEFA"],
  ["baby-shower", "bs41-big-news", "baby_shower", null, "Big news, little one", "Congratulations!", "#FFF3DC"],
  ["baby-shower", "bs42-ocean-love", "baby_shower", null, "An ocean of love", "Happy baby shower", "#D6F5EA"],
  ["baby-shower", "bs43-counting-sheep", "baby_shower", null, "Counting down!", "Baby is almost here", "#5A499C"],
  ["baby-shower", "bs44-pitter-patter", "baby_shower", null, "Pitter patter", "Little feet coming soon", "#D6F5EA"],
  ["baby-shower", "bs45-milk-cuddles", "baby_shower", null, "Milk & cuddles", "Happy baby shower", "#FBCFDF"],
  ["baby-shower", "bs46-baby-steps", "baby_shower", null, "Baby steps", "The adventure begins", "#E6DEFA"],
  ["baby-shower", "bs47-dream-big", "baby_shower", null, "Dream big, little one", "Happy baby shower", "#5A499C"],
  ["baby-shower", "bs48-ready-to-rattle", "baby_shower", null, "Ready to rattle!", "Baby is nearly here", "#FFF3DC"],
  ["baby-shower", "bs49-puppy-love", "baby_shower", null, "Puppy love", "For the new little one", "#E6DEFA"],
  ["baby-shower", "bs50-nap-time", "baby_shower", null, "Nap time soon!", "Happy baby shower", "#D6F5EA"],
  ["graduation", "gr1-cap", "graduation", null, "Hats off to you!", "Congratulations, graduate!", "#FFF3DC"],
  ["graduation", "gr2-cap-toss", "graduation", null, "You did it!", "Congratulations, grad", "#CFE8F7"],
  ["graduation", "gr3-diploma", "graduation", null, "Class act!", "Congratulations on graduating", "#E6DEFA"],
  ["graduation", "gr6-bear", "graduation", null, "Beary proud!", "Congratulations, graduate", "#FBCFDF"],
  ["graduation", "mc-gr6-mountain", "graduation", null, "Onwards & upwards", "CONGRATULATIONS", "#CDEDE8"],
  ["graduation", "gr9-star", "graduation", null, "Star graduate!", "You shine bright", "#5A499C"],
  ["graduation", "gr5-owl", "graduation", null, "Whoo’s a grad?", "You are! Congratulations", "#D6F5EA"],
  ["graduation", "ad-gr4-briefcase", "graduation", null, "Hello, real world", "GRADUATE", "#F4F1EA"],
  ["graduation", "ar-gr6-linocut", "graduation", null, "NEXT LEVEL UNLOCKED", "", "#F6EFE2"],
  ["graduation", "gr27-tick", "graduation", null, "Degree: done!", "Congratulations, graduate", "#D6F5EA"],
  ["graduation", "mc-gr9-fireworks", "graduation", null, "Time to celebrate", "CLASS OF 2026", "#1F2A44"],
  ["graduation", "gr14-rocket", "graduation", null, "Blast off, grad!", "The future is yours", "#D6F5EA"],
  ["graduation", "gr13-rosette", "graduation", null, "First class!", "Congratulations", "#D6F5EA"],
  ["graduation", "ar-gr5-painted-pattern", "graduation", null, "Proud of you!", "", "#FFF4E6"],
  ["graduation", "gr16-bulb", "graduation", null, "Bright future!", "Congratulations, grad", "#5A499C"],
  ["graduation", "mc-gr5-plane", "graduation", null, "The future is yours", "GRADUATE", "#1F2A44"],
  ["graduation", "mc-gr1-cap", "graduation", null, "Hats off to you", "CONGRATULATIONS", "#DDE6FA"],
  ["graduation", "ad-gr8-diploma", "graduation", null, "You did it!", "CLASS OF 2026", "#3C5A80"],
  ["graduation", "gr4-books", "graduation", null, "Top of the class!", "So proud of you", "#FFF3DC"],
  ["graduation", "gr7-cat", "graduation", null, "Purr-fectly done!", "Congratulations!", "#E6DEFA"],
  ["graduation", "gr8-bunny", "graduation", null, "Hop to the top!", "Congratulations, grad", "#D6F5EA"],
  ["graduation", "ar-gr10-watercolour-meadow", "graduation", null, "Congratulations", "GRADUATE", "#FBF8F2"],
  ["graduation", "ad-gr9-mountain", "graduation", null, "Onwards & upwards", "CONGRATULATIONS", "#CDEDE8"],
  ["graduation", "gr10-pencil", "graduation", null, "Pencils down!", "You made it. Congratulations!", "#E6DEFA"],
  ["graduation", "gr11-trophy", "graduation", null, "Top marks!", "Congratulations, graduate", "#FFF3DC"],
  ["graduation", "mc-gr10-star", "graduation", null, "Reach for the stars", "CONGRATULATIONS", "#DDE6FA"],
  ["graduation", "ar-gr2-linocut", "graduation", null, "CLASS OF 2026", "", "#F3ECDB"],
  ["graduation", "gr12-medal", "graduation", null, "Gold star graduate", "So proud of you", "#E6DEFA"],
  ["graduation", "gr15-mountain", "graduation", null, "Onwards & upwards!", "Congratulations, graduate", "#FFF3DC"],
  ["graduation", "ad-gr10-fireworks", "graduation", null, "Time to celebrate!", "CLASS OF 2026", "#1F2A44"],
  ["graduation", "gr17-globe", "graduation", null, "The world awaits!", "Congratulations!", "#5A499C"],
  ["graduation", "ar-gr9-painted-pattern", "graduation", null, "Smart cookie!", "", "#1E5E5E"],
  ["graduation", "ad-gr7-plane", "graduation", null, "The world awaits", "GRADUATE", "#DDE6FA"],
  ["graduation", "gr18-compass", "graduation", null, "Find your way!", "Congratulations, graduate", "#FFF3DC"],
  ["graduation", "ad-gr3-career", "graduation", null, "Career mode: on", "CONGRATULATIONS", "#CDEDE8"],
  ["graduation", "gr19-plane", "graduation", null, "Fly high, grad!", "So proud of you", "#5A499C"],
  ["graduation", "mc-gr2-diploma", "graduation", null, "You did it!", "CLASS OF 2026", "#1F2A44"],
  ["graduation", "gr20-door", "graduation", null, "New chapter!", "Congratulations, graduate", "#5A499C"],
  ["graduation", "ar-gr7-watercolour-wreath", "graduation", null, "You did it!", "CLASS OF 2026", "#FBF8F2"],
  ["graduation", "gr21-sunrise", "graduation", null, "Bright days ahead", "Congratulations!", "#E6DEFA"],
  ["graduation", "gr22-balloon", "graduation", null, "Up, up & away!", "Congratulations, grad", "#D6F5EA"],
  ["graduation", "mc-gr7-trophy", "graduation", null, "Graduate with honours", "CONGRATULATIONS", "#E7E2F6"],
  ["graduation", "ad-gr1-cap", "graduation", null, "Hats off to you!", "CONGRATULATIONS", "#DDE6FA"],
  ["graduation", "gr23-shooting-star", "graduation", null, "Reach for the stars!", "Congratulations", "#5A499C"],
  ["graduation", "ar-gr4-painted-scene-sunset", "graduation", null, "Congratulations the future is bright", "", "#C2457A"],
  ["graduation", "mc-gr8-compass", "graduation", null, "Find your way", "CONGRATULATIONS", "#E6ECEF"],
  ["graduation", "gr24-fireworks", "graduation", null, "Grad party!", "Time to celebrate", "#5A499C"],
  ["graduation", "gr25-podium", "graduation", null, "Number one grad!", "Congratulations", "#FFF3DC"],
  ["graduation", "ad-gr5-city", "graduation", null, "Big city, big dreams", "CONGRATULATIONS", "#1F2A44"],
  ["graduation", "ar-gr3-watercolour-border", "graduation", null, "Hats off to you", "CONGRATULATIONS", "#FBF8F2"],
  ["graduation", "gr26-popper", "graduation", null, "Pop the cork!", "You graduated!", "#E6DEFA"],
  ["graduation", "gr28-bear-lilac", "graduation", null, "Clever cub!", "Congratulations", "#FFF3DC"],
  ["graduation", "mc-gr4-cap-light", "graduation", null, "Class act", "CONGRATULATIONS", "#3C5A80"],
  ["graduation", "gr29-cat-cream", "graduation", null, "Smarty paws!", "Congratulations, grad", "#FBCFDF"],
  ["graduation", "ad-gr2-rocket", "graduation", null, "The future is bright", "CLASS OF 2026", "#1F2A44"],
  ["graduation", "gr30-class-of", "graduation", null, "Class of 2026", "Congratulations!", "#E6DEFA"],
  ["graduation", "ar-gr8-painted-scene-dawn", "graduation", null, "Reach for the stars congrats grad", "", "#F2A7B8"],
  ["graduation", "mc-gr3-books", "graduation", null, "Top of the class", "CONGRATULATIONS", "#F4F1EA"],
  ["graduation", "ad-gr6-stairs", "graduation", null, "Next level unlocked", "CONGRATULATIONS", "#E7E2F6"],
  ["graduation", "ar-gr1-painted-pattern", "graduation", null, "Congrats Grad!", "", "#1F2A55"],
];
