// GENERATED from frontend/public/cards/illustrated — do not edit by hand.
// Regenerate with the gen_registry script if covers are added or re-ordered.
// Row: [folder, file stem, occasion id, sympathy group, headline, tagline, background]
// Order inside each folder is curated: the first 10 are the lead covers used on
// landing pages, the rest follow in natural file order.
export const ILLUSTRATED_COVER_ROWS = [
  ["birthday", "b1-cake", "birthday", null, "Happy birthday!", "Make a wish (or three)", "#FFF3DC"],
  ["birthday", "2a-cake", "birthday", null, "Happy Birthday!", "", "#5A499C"],
  ["birthday", "b2-balloons", "birthday", null, "Hip hip hooray!", "It’s your big day!", "#E6DEFA"],
  ["birthday", "b3-gift", "birthday", null, "Surprise!", "Happy birthday, you legend", "#5A499C"],
  ["birthday", "b5-party-hat", "birthday", null, "Let’s party!", "Happy birthday!", "#FBCFDF"],
  ["birthday", "bd3-crown", "birthday", null, "Birthday royalty", "Rule the day!", "#5A499C"],
  ["birthday", "b10-birthday-star", "birthday", null, "Birthday superstar!", "Shine bright today", "#5A499C"],
  ["birthday", "2b-balloons", "birthday", null, "Hooray!", "It’s your day!", "#FFF3DC"],
  ["birthday", "b4-cupcake", "birthday", null, "Sweet as a cupcake", "Have the sweetest birthday", "#D6F5EA"],
  ["birthday", "bd2-presents", "birthday", null, "Gifts galore!", "Happy birthday, you!", "#FFF3DC"],
  ["birthday", "b6-donut", "birthday", null, "Donut worry, be happy", "Happy birthday!", "#FFF3DC"],
  ["birthday", "b7-ice-cream", "birthday", null, "Have a cool birthday!", "Treat yourself today", "#E6DEFA"],
  ["birthday", "b8-popper", "birthday", null, "Pop pop!", "It’s your birthday!", "#FFF3DC"],
  ["birthday", "b9-party-cat", "birthday", null, "Happy purr-thday!", "Have a paw-some day", "#FBCFDF"],
  ["birthday", "bd1-cake-slice", "birthday", null, "A slice of birthday fun", "Happy birthday!", "#E6DEFA"],
  ["birthday", "bd4-blower", "birthday", null, "Toot toot!", "It’s your birthday!", "#D6F5EA"],
  ["birthday", "bd5-party-dog", "birthday", null, "Happy bark-day!", "Have a paw-some day", "#FBCFDF"],
  ["birthday", "bd6-party-bunny", "birthday", null, "Some-bunny’s birthday!", "Hop hop hooray", "#E6DEFA"],
  ["birthday", "bd7-lollipop", "birthday", null, "You’re so sweet!", "Happy birthday", "#FFF3DC"],
  ["birthday", "bd8-bunting", "birthday", null, "Party time!", "Happy birthday!", "#D6F5EA"],
  ["birthday", "bd9-macarons", "birthday", null, "Stack up the fun!", "Happy birthday", "#FBCFDF"],
  ["birthday", "bd10-sunny", "birthday", null, "Hello, sunshine!", "Have a bright birthday", "#E6DEFA"],
  ["farewell", "3t-farewell-legend", "leaving", null, "Farewell, legend!", "Thanks for everything. You’ll be so missed!", "#FFF3DC"],
  ["farewell", "3l-teary-cat", "leaving", null, "We’ll miss you!", "Don’t be a stranger", "#FFF3DC"],
  ["farewell", "fw3-airplane", "leaving", null, "Up, up and away!", "Bon voyage from the team", "#5A499C"],
  ["farewell", "3n-new-door", "leaving", null, "Hello, next chapter!", "So proud of you. Go get it!", "#5A499C"],
  ["farewell", "3s-rainbow", "leaving", null, "Sad you’re going, happy for you!", "We’ll miss you loads", "#5A499C"],
  ["farewell", "fw1-moving-box", "leaving", null, "Packing up, moving on!", "We’ll miss you loads", "#FFF3DC"],
  ["farewell", "fw10-map-pin", "leaving", null, "Next stop: awesome!", "Good luck in your new role", "#FBCFDF"],
  ["farewell", "3r-signpost", "leaving", null, "Onwards & upwards!", "Good luck in the new role", "#FBCFDF"],
  ["farewell", "3m-suitcase", "leaving", null, "Adventure awaits!", "Good luck on your next journey", "#E6DEFA"],
  ["farewell", "3o-blast-off", "leaving", null, "Blast off!", "To your next big thing", "#D6F5EA"],
  ["farewell", "3k-paper-plane", "leaving", null, "Off you go!", "We’ll miss you loads", "#5A499C"],
  ["farewell", "3p-keep-growing", "leaving", null, "Keep growing!", "Can’t wait to see you bloom", "#E6DEFA"],
  ["farewell", "3q-coffee-buddy", "leaving", null, "Coffee won’t taste the same", "without you. Good luck!", "#FFF3DC"],
  ["farewell", "fw2-road-trip", "leaving", null, "New road, new ride!", "Good luck out there", "#D6F5EA"],
  ["farewell", "fw4-sunrise", "leaving", null, "A new day begins!", "Good luck on the next one", "#E6DEFA"],
  ["farewell", "fw5-balloon-trip", "leaving", null, "Soar high!", "We’ll miss you", "#D6F5EA"],
  ["farewell", "fw6-compass", "leaving", null, "Follow your compass", "Good luck on your next adventure", "#FFF3DC"],
  ["farewell", "fw7-globe", "leaving", null, "The world is yours!", "Go get it", "#5A499C"],
  ["farewell", "fw8-sailboat", "leaving", null, "Smooth sailing!", "Wishing you the best", "#D6F5EA"],
  ["farewell", "fw9-bindle-bird", "leaving", null, "Fly high, friend!", "The nest won’t be the same", "#E6DEFA"],
  ["retirement", "rt1-beach", "retirement", null, "Happy retirement!", "Sun, sand, no emails", "#E6DEFA"],
  ["retirement", "rt6-alarm", "retirement", null, "No more alarms!", "Happy retirement", "#E6DEFA"],
  ["retirement", "rt4-rocking-chair", "retirement", null, "Rock on, retiree!", "You’ve earned it", "#FFF3DC"],
  ["retirement", "rt8-camper", "retirement", null, "Adventure o’clock!", "Happy retirement!", "#5A499C"],
  ["retirement", "rt2-hammock", "retirement", null, "Time to relax!", "Happy retirement", "#FFF3DC"],
  ["retirement", "rt3-golf", "retirement", null, "Tee time, every day!", "Happy retirement!", "#E6DEFA"],
  ["retirement", "rt5-coconut", "retirement", null, "Cheers to forever off!", "Happy retirement", "#D6F5EA"],
  ["retirement", "rt7-watering-can", "retirement", null, "Grow your next chapter", "Happy retirement!", "#FFF3DC"],
  ["retirement", "rt9-book-tea", "retirement", null, "Chapter free time", "Happy retirement", "#FBCFDF"],
  ["retirement", "rt10-slippers", "retirement", null, "Slippers on!", "Enjoy every lazy morning", "#E6DEFA"],
  ["anniversary", "a1-rings", "anniversary", null, "Happy anniversary!", "Here’s to many more", "#FFF3DC"],
  ["anniversary", "a3-mugs", "anniversary", null, "Another year of us", "Happy anniversary", "#5A499C"],
  ["anniversary", "a10-cheers", "anniversary", null, "Cheers to us!", "Happy anniversary!", "#FBCFDF"],
  ["anniversary", "a2-lovebirds", "anniversary", null, "Still lovebirds", "Happy anniversary!", "#FBCFDF"],
  ["anniversary", "a4-penguins", "anniversary", null, "Still my penguin", "Happy anniversary!", "#E6DEFA"],
  ["anniversary", "a5-lock", "anniversary", null, "You hold the key", "Happy anniversary, love", "#D6F5EA"],
  ["anniversary", "a7-calendar", "anniversary", null, "365 more days of us", "Happy anniversary!", "#E6DEFA"],
  ["anniversary", "a8-two-plants", "anniversary", null, "Growing together", "Happy anniversary!", "#FFF3DC"],
  ["anniversary", "an1-heart-chain", "anniversary", null, "Still linked", "Happy anniversary", "#FFF3DC"],
  ["anniversary", "a9-heart-balloons", "anniversary", null, "Love you more!", "Happy anniversary", "#D6F5EA"],
  ["anniversary", "a6-heart-balloon", "anniversary", null, "Up, up & away!", "Happy anniversary!", "#FFF3DC"],
  ["anniversary", "an2-socks", "anniversary", null, "Perfect pair", "Happy anniversary!", "#E6DEFA"],
  ["anniversary", "an3-shakers", "anniversary", null, "Better together", "Happy anniversary", "#D6F5EA"],
  ["anniversary", "an4-avocado", "anniversary", null, "My other half", "Happy anniversary!", "#FBCFDF"],
  ["anniversary", "an5-puzzle", "anniversary", null, "We just fit!", "Happy anniversary", "#E6DEFA"],
  ["anniversary", "an6-coffee-donut", "anniversary", null, "You go with me", "Happy anniversary", "#5A499C"],
  ["anniversary", "an7-hourglass", "anniversary", null, "Time flies with you", "Happy anniversary!", "#FFF3DC"],
  ["anniversary", "an8-jars", "anniversary", null, "Perfect match", "Happy anniversary", "#D6F5EA"],
  ["anniversary", "an9-bees", "anniversary", null, "Bee mine, always", "Happy anniversary", "#E6DEFA"],
  ["anniversary", "an10-flowers", "anniversary", null, "Growing in love", "Happy anniversary!", "#FBCFDF"],
  ["wedding", "wd1-bells", "wedding", null, "Wedding bells!", "Congratulations, you two", "#E6DEFA"],
  ["wedding", "3e-just-married-car", "wedding", null, "Just married!", "Beep beep! Congrats!", "#FFF3DC"],
  ["wedding", "2d-the-ring", "wedding", null, "Happily ever after", "Congrats, you two!", "#FFF3DC"],
  ["wedding", "wd4-bottle", "wedding", null, "Pop the bubbly!", "Here’s to the happy couple", "#5A499C"],
  ["wedding", "3b-wedding-cake", "wedding", null, "Sweetest day ever!", "Congratulations, you two!", "#FFF3DC"],
  ["wedding", "wd7-arch", "wedding", null, "Two hearts, one love", "Congratulations!", "#E6DEFA"],
  ["wedding", "2c-cheers", "wedding", null, "Cheers to love!", "Just married", "#E6DEFA"],
  ["wedding", "3a-lovebirds", "wedding", null, "Lovebirds!", "Wishing you a lifetime of cosy together", "#E6DEFA"],
  ["wedding", "wd6-bears", "wedding", null, "Beary in love", "Happy wedding day!", "#FFF3DC"],
  ["wedding", "3c-penguins", "wedding", null, "You found your penguin", "Happy wedding day!", "#D6F5EA"],
  ["wedding", "3d-love-letter", "wedding", null, "Sealed with love", "", "#5A499C"],
  ["wedding", "3f-purrfect-match", "wedding", null, "Purrfect match!", "Congrats on the big day", "#FBCFDF"],
  ["wedding", "3g-love-is-in-the-air", "wedding", null, "Love is in the air!", "", "#E6DEFA"],
  ["wedding", "3h-better-together", "wedding", null, "Better together", "Here’s to every morning, side by side", "#5A499C"],
  ["wedding", "3i-bouquet", "wedding", null, "Here’s to forever", "With love on your wedding day", "#FFF3DC"],
  ["wedding", "3j-two-peas", "wedding", null, "Two peas in a pod!", "Made for each other. Congratulations!", "#E6DEFA"],
  ["wedding", "wd2-swans", "wedding", null, "Love birds", "Happy wedding day", "#D6F5EA"],
  ["wedding", "wd3-outfits", "wedding", null, "Ready, set, I do!", "Congratulations!", "#FFF3DC"],
  ["wedding", "wd5-bunnies", "wedding", null, "Hoppily ever after", "Congratulations!", "#FBCFDF"],
  ["wedding", "wd8-heart-cluster", "wedding", null, "All the love!", "Happy wedding day", "#5A499C"],
  ["wedding", "wd9-two-candles", "wedding", null, "Two flames, one heart", "Congratulations", "#FBCFDF"],
  ["wedding", "wd10-otters", "wedding", null, "Otterly in love", "Happy wedding day!", "#D6F5EA"],
  ["christmas", "xm1-tree", "christmas", null, "Merry Christmas!", "Wishing you a cosy season", "#FFF3DC"],
  ["christmas", "xm25-tree-night", "christmas", null, "Tree-mendous Christmas!", "Happy holidays", "#5A499C"],
  ["christmas", "xm12-wreath", "christmas", null, "Merry & bright!", "Season’s greetings", "#FFF3DC"],
  ["christmas", "xm3-snowman", "christmas", null, "Let it snow!", "Merry Christmas & happy new year", "#E6DEFA"],
  ["christmas", "xm6-reindeer", "christmas", null, "Oh deer, it’s Christmas!", "Have a merry one", "#5A499C"],
  ["christmas", "xm2-ornament", "christmas", null, "Have a ball this Christmas!", "Merry Christmas", "#5A499C"],
  ["christmas", "xm11-cocoa", "christmas", null, "Cosy Christmas!", "Warm wishes to you", "#E6DEFA"],
  ["christmas", "xm21-presents", "christmas", null, "Wrapped with love", "Merry Christmas", "#D6F5EA"],
  ["christmas", "xm20-gingerbread-house", "christmas", null, "Home for the holidays", "Merry Christmas", "#E6DEFA"],
  ["christmas", "xm15-holly", "christmas", null, "Holly jolly!", "Merry Christmas", "#FFF3DC"],
  ["christmas", "xm4-gingerbread", "christmas", null, "Oh snap!", "Merry Christmas", "#FFF3DC"],
  ["christmas", "xm5-stocking", "christmas", null, "Stocking full of joy", "Merry Christmas!", "#D6F5EA"],
  ["christmas", "xm7-santa-cat", "christmas", null, "Meowy Christmas!", "Have a purr-fect holiday", "#FBCFDF"],
  ["christmas", "xm8-reindeer-dog", "christmas", null, "Yappy holidays!", "Merry Christmas", "#E6DEFA"],
  ["christmas", "xm9-candy-cane", "christmas", null, "Sweet season!", "Merry Christmas", "#FFF3DC"],
  ["christmas", "xm10-snowflake", "christmas", null, "Snow much fun!", "Happy holidays", "#5A499C"],
  ["christmas", "xm13-mittens", "christmas", null, "Warm wishes", "Merry Christmas", "#5A499C"],
  ["christmas", "xm14-sleigh", "christmas", null, "Sleigh all day!", "Merry Christmas!", "#D6F5EA"],
  ["christmas", "xm16-cookies", "christmas", null, "Milk & cookies!", "Leave some for Santa", "#E6DEFA"],
  ["christmas", "xm17-snow-globe", "christmas", null, "Shake up some joy!", "Merry Christmas", "#FBCFDF"],
  ["christmas", "xm18-lights", "christmas", null, "Merry & bright", "Happy holidays", "#5A499C"],
  ["christmas", "xm19-fox", "christmas", null, "Fox-tastic Christmas!", "Warm wishes", "#FFF3DC"],
  ["christmas", "xm22-bells", "christmas", null, "Jingle all the way!", "Merry Christmas", "#FBCFDF"],
  ["christmas", "xm23-star", "christmas", null, "Shine bright!", "Merry Christmas", "#5A499C"],
  ["christmas", "xm24-bauble-lilac", "christmas", null, "Merry everything!", "And a happy new year", "#FFF3DC"],
  ["congratulations", "c4-fireworks", "congratulations", null, "Congrats!", "What a moment!", "#5A499C"],
  ["congratulations", "c1-trophy", "congratulations", null, "You did it!", "Congratulations!", "#FFF3DC"],
  ["congratulations", "c8-popper", "congratulations", null, "Big congrats!", "Time to celebrate", "#E6DEFA"],
  ["congratulations", "c10-champagne", "congratulations", null, "Cheers to you!", "Congratulations!", "#E6DEFA"],
  ["congratulations", "c9-star", "congratulations", null, "You’re a star!", "Well done, you!", "#FFF3DC"],
  ["congratulations", "c2-medal", "congratulations", null, "Gold star effort!", "So proud of you", "#E6DEFA"],
  ["congratulations", "c5-rocket", "congratulations", null, "Sky’s the limit!", "Congratulations on your success", "#D6F5EA"],
  ["congratulations", "cg1-podium", "congratulations", null, "Number one!", "Congratulations, champ", "#FFF3DC"],
  ["congratulations", "cg3-big-tick", "congratulations", null, "Nailed it!", "Big congrats!", "#E6DEFA"],
  ["congratulations", "cg2-shooting-star", "congratulations", null, "Star power!", "Congratulations!", "#5A499C"],
  ["congratulations", "c3-rosette", "congratulations", null, "Way to go!", "Congratulations, superstar", "#D6F5EA"],
  ["congratulations", "c6-mountain", "congratulations", null, "Top of the world!", "Congrats on the big climb", "#FFF3DC"],
  ["congratulations", "c7-grad-cap", "congratulations", null, "Hats off to you!", "Congratulations, graduate!", "#FBCFDF"],
  ["congratulations", "cg4-new-home", "congratulations", null, "Home sweet home", "Congrats on your new place", "#D6F5EA"],
  ["congratulations", "cg5-new-baby", "congratulations", null, "Welcome, little one!", "Congratulations on your baby", "#FBCFDF"],
  ["congratulations", "cg6-crown", "congratulations", null, "You’re the queen!", "Congratulations!", "#E6DEFA"],
  ["congratulations", "cg7-bubbly", "congratulations", null, "Pop! Congrats!", "Time to celebrate", "#FFF3DC"],
  ["congratulations", "cg8-cloud-nine", "congratulations", null, "On cloud nine!", "Congratulations!", "#E6DEFA"],
  ["congratulations", "cg9-bright-idea", "congratulations", null, "Bright spark!", "Congrats on your success", "#5A499C"],
  ["congratulations", "cg10-you-rock", "congratulations", null, "You rock!", "Congratulations!", "#D6F5EA"],
  ["get-well", "gw2-thermometer", "get_well", null, "Get well soon!", "Rest up, we miss you", "#E6DEFA"],
  ["get-well", "gw20-flowers", "get_well", null, "Get well soon", "", "#FFF3DC"],
  ["get-well", "gw1-soup", "get_well", null, "Souper get well!", "Feel better soon", "#FFF3DC"],
  ["get-well", "gw12-teddy", "get_well", null, "Beary get well!", "Feel better soon", "#FBCFDF"],
  ["get-well", "gw16-moon", "get_well", null, "Sleep well, heal well", "Get well soon", "#5A499C"],
  ["get-well", "gw11-vase", "get_well", null, "Get well blooms", "Thinking of you", "#FFF3DC"],
  ["get-well", "gw14-sun-cloud", "get_well", null, "Sunnier days ahead", "Feel better soon", "#D6F5EA"],
  ["get-well", "gw7-tea-lemon", "get_well", null, "Sip, rest, repeat", "Feel better soon", "#E6DEFA"],
  ["get-well", "gw3-plaster", "get_well", null, "Patching you up", "Get well soon!", "#D6F5EA"],
  ["get-well", "gw13-cat-blanket", "get_well", null, "Cosy up & rest", "Get well soon", "#E6DEFA"],
  ["get-well", "gw4-tissues", "get_well", null, "Achoo!", "Bless you. Feel better soon", "#FBCFDF"],
  ["get-well", "gw5-hot-water-bottle", "get_well", null, "Warm wishes", "Get well soon", "#E6DEFA"],
  ["get-well", "gw6-bear-bed", "get_well", null, "Rest up, buddy", "Get well soon", "#FFF3DC"],
  ["get-well", "gw8-orange", "get_well", null, "Vitamin C you soon!", "Get well soon", "#D6F5EA"],
  ["get-well", "gw9-apple", "get_well", null, "An apple a day...", "Get well soon!", "#FFF3DC"],
  ["get-well", "gw10-honey", "get_well", null, "Feel better, honey", "Sending sweet wishes", "#E6DEFA"],
  ["get-well", "gw15-socks", "get_well", null, "Feet up, rest up!", "Get well soon", "#FFF3DC"],
  ["get-well", "gw17-ice-pack", "get_well", null, "Ruff day?", "Hope you feel better soon", "#E6DEFA"],
  ["get-well", "gw18-plant", "get_well", null, "Grow stronger", "Get well soon", "#D6F5EA"],
  ["get-well", "gw19-pillow", "get_well", null, "Rest mode: on", "Get well soon!", "#FBCFDF"],
  ["thank-you", "ty1-big-heart", "thank_you", null, "Thank you!", "From the bottom of our hearts", "#FFF3DC"],
  ["thank-you", "ty9-letter", "thank_you", null, "Thank you!", "", "#5A499C"],
  ["thank-you", "ty2-sunflower", "thank_you", null, "You make us sunny", "Thank you!", "#E6DEFA"],
  ["thank-you", "ty19-cloud-nine", "thank_you", null, "Thanks a million!", "You made our day", "#E6DEFA"],
  ["thank-you", "ty11-trophy", "thank_you", null, "You’re the best!", "Thanks a million", "#FFF3DC"],
  ["thank-you", "ty12-star", "thank_you", null, "Thanks, superstar!", "We couldn’t have done it without you", "#E6DEFA"],
  ["thank-you", "ty16-rainbow", "thank_you", null, "You brighten our days", "Thank you", "#5A499C"],
  ["thank-you", "ty20-bouquet", "thank_you", null, "Thank you kindly", "With gratitude", "#FBCFDF"],
  ["thank-you", "ty17-balloons", "thank_you", null, "Thanks a bunch!", "You’re amazing", "#FFF3DC"],
  ["thank-you", "ty3-bee", "thank_you", null, "Thank bee-you!", "You’re the bee’s knees", "#D6F5EA"],
  ["thank-you", "ty4-owl", "thank_you", null, "Owl-ways grateful", "Thank you so much", "#FFF3DC"],
  ["thank-you", "ty5-cactus", "thank_you", null, "Thanks a lot!", "You’re a real sharp one", "#E6DEFA"],
  ["thank-you", "ty6-latte", "thank_you", null, "Thanks a latte!", "We appreciate you", "#FBCFDF"],
  ["thank-you", "ty7-melon", "thank_you", null, "One in a melon!", "Thank you", "#D6F5EA"],
  ["thank-you", "ty8-berry", "thank_you", null, "Thank you berry much", "", "#E6DEFA"],
  ["thank-you", "ty10-gift", "thank_you", null, "You’re a gift!", "Thank you for everything", "#D6F5EA"],
  ["thank-you", "ty13-hug", "thank_you", null, "Thanks for the hugs", "You’re the best", "#FBCFDF"],
  ["thank-you", "ty14-cupcake", "thank_you", null, "So sweet of you!", "Thank you", "#FFF3DC"],
  ["thank-you", "ty15-donut", "thank_you", null, "Donut know what we’d do", "without you. Thank you!", "#E6DEFA"],
  ["thank-you", "ty18-tulips", "thank_you", null, "You help us grow", "Thank you", "#D6F5EA"],
  ["sympathy-colleague", "s1-candle", "sympathy", "colleague", "Thinking of you", "With love from all of us", "#E6DEFA"],
  ["sympathy-colleague", "s7-forget-me-not", "sympathy", "colleague", "Sorry for your loss", "", "#D6F5EA"],
  ["sympathy-colleague", "s2-dove", "sympathy", "colleague", "With deepest sympathy", "We’re here for you", "#D6F5EA"],
  ["sympathy-colleague", "s4-moon", "sympathy", "colleague", "Holding you in our hearts", "From all of us", "#5A499C"],
  ["sympathy-colleague", "s6-lanterns", "sympathy", "colleague", "With love & light", "Our thoughts are with you", "#5A499C"],
  ["sympathy-colleague", "s5-hug", "sympathy", "colleague", "Sending big hugs", "Thinking of you", "#FBCFDF"],
  ["sympathy-colleague", "s3-teacup", "sympathy", "colleague", "Here for you", "Take all the time you need", "#FFF3DC"],
  ["sympathy-colleague", "s10-branch-bird", "sympathy", "colleague", "You’re not alone", "With love from all of us", "#E6DEFA"],
  ["sympathy-colleague", "s8-tulips", "sympathy", "colleague", "Wishing you gentle days", "With love from the team", "#E6DEFA"],
  ["sympathy-colleague", "s9-feather", "sympathy", "colleague", "Softly thinking of you", "We’re all here for you", "#FFF3DC"],
  ["sympathy-partner", "l6-candle", "sympathy", "partner", "Remembering with love", "Thinking of you always", "#FBCFDF"],
  ["sympathy-partner", "l1-moon-stars", "sympathy", "partner", "Love never ends", "Thinking of you", "#5A499C"],
  ["sympathy-partner", "l2-lanterns", "sympathy", "partner", "Their light lives on", "Holding you close", "#E6DEFA"],
  ["sympathy-partner", "l3-two-stars", "sympathy", "partner", "Always with you", "With deepest sympathy", "#5A499C"],
  ["sympathy-partner", "l4-heart-tree", "sympathy", "partner", "Love lives on", "Wrapped in love", "#FFF3DC"],
  ["sympathy-partner", "l7-dove", "sympathy", "partner", "With deepest love", "We are here for you", "#E6DEFA"],
  ["sympathy-partner", "l8-forget-me-not", "sympathy", "partner", "Forever remembered", "", "#FFF3DC"],
  ["sympathy-partner", "l10-hug", "sympathy", "partner", "Sending all our love", "Thinking of you", "#E6DEFA"],
  ["sympathy-partner", "l5-feather", "sympathy", "partner", "Gentle hugs for you", "We’re so sorry", "#E6DEFA"],
  ["sympathy-partner", "l9-rainbow", "sympathy", "partner", "Holding you in our hearts", "With love", "#D6F5EA"],
  ["sympathy-tears", "st1-rain-cloud", "sympathy", "comfort", "So sorry for your loss", "Sending you gentle hugs", "#E6DEFA"],
  ["sympathy-tears", "st4-teary-cat", "sympathy", "comfort", "Thinking of you", "With love and hugs", "#FBCFDF"],
  ["sympathy-tears", "st2-teary-bear", "sympathy", "comfort", "Beary big hugs", "Thinking of you", "#FFF3DC"],
  ["sympathy-tears", "st8-sun-cloud", "sympathy", "comfort", "Brighter days will come", "Thinking of you", "#E6DEFA"],
  ["sympathy-tears", "st7-mended-heart", "sympathy", "comfort", "Healing hugs", "Take all the time you need", "#FFF3DC"],
  ["sympathy-tears", "st5-teary-bunny", "sympathy", "comfort", "Hugs for you", "Sorry you’re hurting", "#E6DEFA"],
  ["sympathy-tears", "st3-teary-puppy", "sympathy", "comfort", "Sending puppy hugs", "We’re here for you", "#D6F5EA"],
  ["sympathy-tears", "st10-teary-duck", "sympathy", "comfort", "Sending love", "We’re thinking of you", "#D6F5EA"],
  ["sympathy-tears", "st6-teary-penguin", "sympathy", "comfort", "Here with tissues", "And a big hug", "#D6F5EA"],
  ["sympathy-tears", "st9-teary-koala", "sympathy", "comfort", "Koala-ty hugs", "We’re so sorry", "#FBCFDF"],
  ["sympathy-pet", "p3-paw-heart", "sympathy", "pet", "Paw prints on your heart", "Thinking of you", "#5A499C"],
  ["sympathy-pet", "p4-rainbow-bridge", "sympathy", "pet", "Run free, sweet friend", "Until the rainbow bridge", "#E6DEFA"],
  ["sympathy-pet", "p1-sleeping-cat", "sympathy", "pet", "Forever in your heart", "So sorry about your best friend", "#E6DEFA"],
  ["sympathy-pet", "p10-dog-cloud", "sympathy", "pet", "Until we meet again", "With love and sympathy", "#FBCFDF"],
  ["sympathy-pet", "p2-angel-dog", "sympathy", "pet", "Such a good friend", "Sending love at this sad time", "#FFF3DC"],
  ["sympathy-pet", "p5-paw-trail", "sympathy", "pet", "Always by your side", "So sorry for your loss", "#5A499C"],
  ["sympathy-pet", "p8-angel-cat", "sympathy", "pet", "Purring in heaven", "So sorry about your kitty", "#E6DEFA"],
  ["sympathy-pet", "p7-collar", "sympathy", "pet", "Forever loved", "Sending you a big hug", "#D6F5EA"],
  ["sympathy-pet", "p6-bowl", "sympathy", "pet", "They were so loved", "Thinking of you both", "#FFF3DC"],
  ["sympathy-pet", "p9-bunny", "sympathy", "pet", "Little paws, big love", "Thinking of you", "#D6F5EA"],
];
