/**
 * worldCurrencies.js — every currency Lemon Squeezy can show at checkout
 * (docs.lemonsqueezy.com/help/payments/currencies), with the country or
 * region people know it by and a flag.
 *
 * [code, where it is used, ISO country code for the flag (null = no flag)]
 * Currency names come from the browser (Intl.DisplayNames), so they are
 * always spelled correctly and localised.
 */
export const WORLD_CURRENCIES = [
  ['AED', 'United Arab Emirates', 'AE'],
  ['AFN', 'Afghanistan', 'AF'],
  ['ALL', 'Albania', 'AL'],
  ['AMD', 'Armenia', 'AM'],
  ['ANG', 'Curaçao, Sint Maarten', 'CW'],
  ['AOA', 'Angola', 'AO'],
  ['ARS', 'Argentina', 'AR'],
  ['AUD', 'Australia', 'AU'],
  ['AWG', 'Aruba', 'AW'],
  ['AZN', 'Azerbaijan', 'AZ'],
  ['BAM', 'Bosnia and Herzegovina', 'BA'],
  ['BBD', 'Barbados', 'BB'],
  ['BDT', 'Bangladesh', 'BD'],
  ['BGN', 'Bulgaria', 'BG'],
  ['BIF', 'Burundi', 'BI'],
  ['BMD', 'Bermuda', 'BM'],
  ['BND', 'Brunei', 'BN'],
  ['BOB', 'Bolivia', 'BO'],
  ['BRL', 'Brazil', 'BR'],
  ['BSD', 'Bahamas', 'BS'],
  ['BWP', 'Botswana', 'BW'],
  ['BZD', 'Belize', 'BZ'],
  ['CAD', 'Canada', 'CA'],
  ['CDF', 'DR Congo', 'CD'],
  ['CHF', 'Switzerland, Liechtenstein', 'CH'],
  ['CLP', 'Chile', 'CL'],
  ['CNY', 'China', 'CN'],
  ['COP', 'Colombia', 'CO'],
  ['CRC', 'Costa Rica', 'CR'],
  ['CVE', 'Cape Verde', 'CV'],
  ['CZK', 'Czech Republic', 'CZ'],
  ['DJF', 'Djibouti', 'DJ'],
  ['DKK', 'Denmark', 'DK'],
  ['DOP', 'Dominican Republic', 'DO'],
  ['DZD', 'Algeria', 'DZ'],
  ['EGP', 'Egypt', 'EG'],
  ['ETB', 'Ethiopia', 'ET'],
  ['EUR', 'Eurozone (Germany, France, Ireland, Italy, Spain…)', 'EU'],
  ['FJD', 'Fiji', 'FJ'],
  ['FKP', 'Falkland Islands', 'FK'],
  ['GBP', 'United Kingdom', 'GB'],
  ['GEL', 'Georgia', 'GE'],
  ['GIP', 'Gibraltar', 'GI'],
  ['GMD', 'Gambia', 'GM'],
  ['GNF', 'Guinea', 'GN'],
  ['GTQ', 'Guatemala', 'GT'],
  ['GYD', 'Guyana', 'GY'],
  ['HKD', 'Hong Kong', 'HK'],
  ['HNL', 'Honduras', 'HN'],
  ['HTG', 'Haiti', 'HT'],
  ['HUF', 'Hungary', 'HU'],
  ['IDR', 'Indonesia', 'ID'],
  ['ILS', 'Israel', 'IL'],
  ['INR', 'India', 'IN'],
  ['ISK', 'Iceland', 'IS'],
  ['JMD', 'Jamaica', 'JM'],
  ['JPY', 'Japan', 'JP'],
  ['KES', 'Kenya', 'KE'],
  ['KGS', 'Kyrgyzstan', 'KG'],
  ['KHR', 'Cambodia', 'KH'],
  ['KMF', 'Comoros', 'KM'],
  ['KRW', 'South Korea', 'KR'],
  ['KYD', 'Cayman Islands', 'KY'],
  ['KZT', 'Kazakhstan', 'KZ'],
  ['LAK', 'Laos', 'LA'],
  ['LBP', 'Lebanon', 'LB'],
  ['LKR', 'Sri Lanka', 'LK'],
  ['LRD', 'Liberia', 'LR'],
  ['LSL', 'Lesotho', 'LS'],
  ['MAD', 'Morocco', 'MA'],
  ['MDL', 'Moldova', 'MD'],
  ['MGA', 'Madagascar', 'MG'],
  ['MKD', 'North Macedonia', 'MK'],
  ['MMK', 'Myanmar', 'MM'],
  ['MNT', 'Mongolia', 'MN'],
  ['MOP', 'Macau', 'MO'],
  ['MUR', 'Mauritius', 'MU'],
  ['MVR', 'Maldives', 'MV'],
  ['MWK', 'Malawi', 'MW'],
  ['MXN', 'Mexico', 'MX'],
  ['MYR', 'Malaysia', 'MY'],
  ['MZN', 'Mozambique', 'MZ'],
  ['NAD', 'Namibia', 'NA'],
  ['NGN', 'Nigeria', 'NG'],
  ['NIO', 'Nicaragua', 'NI'],
  ['NOK', 'Norway', 'NO'],
  ['NPR', 'Nepal', 'NP'],
  ['NZD', 'New Zealand', 'NZ'],
  ['PAB', 'Panama', 'PA'],
  ['PEN', 'Peru', 'PE'],
  ['PGK', 'Papua New Guinea', 'PG'],
  ['PHP', 'Philippines', 'PH'],
  ['PKR', 'Pakistan', 'PK'],
  ['PLN', 'Poland', 'PL'],
  ['PYG', 'Paraguay', 'PY'],
  ['QAR', 'Qatar', 'QA'],
  ['RON', 'Romania', 'RO'],
  ['RSD', 'Serbia', 'RS'],
  ['RWF', 'Rwanda', 'RW'],
  ['SAR', 'Saudi Arabia', 'SA'],
  ['SBD', 'Solomon Islands', 'SB'],
  ['SCR', 'Seychelles', 'SC'],
  ['SEK', 'Sweden', 'SE'],
  ['SGD', 'Singapore', 'SG'],
  ['SHP', 'Saint Helena', 'SH'],
  ['SLL', 'Sierra Leone', 'SL'],
  ['SOS', 'Somalia', 'SO'],
  ['SRD', 'Suriname', 'SR'],
  ['SZL', 'Eswatini', 'SZ'],
  ['THB', 'Thailand', 'TH'],
  ['TJS', 'Tajikistan', 'TJ'],
  ['TOP', 'Tonga', 'TO'],
  ['TRY', 'Turkey', 'TR'],
  ['TTD', 'Trinidad and Tobago', 'TT'],
  ['TWD', 'Taiwan', 'TW'],
  ['TZS', 'Tanzania', 'TZ'],
  ['UAH', 'Ukraine', 'UA'],
  ['UGX', 'Uganda', 'UG'],
  ['USD', 'United States', 'US'],
  ['UYU', 'Uruguay', 'UY'],
  ['UZS', 'Uzbekistan', 'UZ'],
  ['VND', 'Vietnam', 'VN'],
  ['VUV', 'Vanuatu', 'VU'],
  ['WST', 'Samoa', 'WS'],
  ['XAF', 'Central Africa (Cameroon, Gabon, Chad…)', null],
  ['XCD', 'Eastern Caribbean (Grenada, St Lucia…)', null],
  ['XOF', 'West Africa (Senegal, Côte d’Ivoire, Benin…)', null],
  ['XPF', 'French Polynesia, New Caledonia', 'PF'],
  ['YER', 'Yemen', 'YE'],
  ['ZAR', 'South Africa', 'ZA'],
  ['ZMW', 'Zambia', 'ZM'],
];

/** Flag emoji from an ISO country code ("IN" → 🇮🇳). */
export const flagFor = (cc) => (cc && /^[A-Z]{2}$/.test(cc)
  ? String.fromCodePoint(...[...cc].map(ch => 0x1F1E6 + ch.charCodeAt(0) - 65))
  : '🌍');

let names = null;
/** "Indian Rupee", from the browser; falls back to the code. */
export function currencyName(code) {
  try {
    if (!names) names = new Intl.DisplayNames(['en'], { type: 'currency' });
    return names.of(code) || code;
  } catch { return code; }
}
